/// Assamese (as) translation dictionary for Seven Sisters Care
const Map<String, String> asDict = {
  // App General
  'appTitle': 'Seven Sisters Care',
  'appSubtitle': 'এআই আধাৰিত জ্ঞানমূলক গেমিং আৰু স্মৃতি সহায়ক মঞ্চ',
  'welcome': 'স্বাগতম',
  'save': 'সংৰক্ষণ কৰক',
  'cancel': 'বাতিল কৰক',
  'close': 'বন্ধ কৰক',
  'back': 'উভতি যাওক',
  'done': 'সম্পূৰ্ণ',
  'submit': 'দাখিল কৰক',
  'next': 'পৰৱৰ্তী',
  'or': 'বা',
  'yes': 'হয়',
  'no': 'নহয়',
  'success': 'সফলতা',
  'error': 'ত্ৰুটি',
  'loading': 'লোড হৈ আছে...',
  'pleaseWait': 'অনুগ্ৰহ কৰি অপেক্ষা কৰক...',

  // Authentication & Role
  'login': 'প্ৰৱেশ কৰক',
  'signUp': 'ছাইন আপ',
  'createAccount': 'একাউণ্ট খোলক',
  'username': 'ব্যৱহাৰকাৰীৰ নাম',
  'enterUsername': 'ব্যৱহাৰকাৰীৰ নাম দিয়ক',
  'password': 'পাছৱৰ্ড',
  'enterPassword': 'পাছৱৰ্ড দিয়ক',
  'confirmPassword': 'পাছৱৰ্ড নিশ্চিত কৰক',
  'dontHaveAccount': 'একাউণ্ট নাই নেকি?',
  'alreadyHaveAccount': 'ইতিমধ্যে একাউণ্ট আছে নেকি?',
  'pleaseEnterUsername': 'অনুগ্ৰহ কৰি ব্যৱহাৰকাৰীৰ নাম দিয়ক',
  'pleaseEnterPassword': 'অনুগ্ৰহ কৰি পাছৱৰ্ড দিয়ক',
  'loginSuccessful': 'লগইন সফল হ’ল',
  'loginFailed': 'লগইন ব্যৰ্থ হ’ল। তথ্যসমূহ পুনৰ পৰীক্ষা কৰক।',
  'connectionError': 'সংযোগ ত্ৰুটি',
  'chooseYourRole': 'আপোনাৰ ভূমিকা বাছক',
  'patient': 'ৰোগী',
  'continueAsPatient': 'ৰোগী হিচাপে আগবাঢ়ক',
  'caregiver': 'সেৱাকাৰী',
  'continueAsCaregiver': 'সেৱাকাৰী হিচাপে আগবাঢ়ক',

  // Patient Registration
  'setupProfile': 'প্ৰফাইল ছেট আপ কৰক',
  'patientDetails': 'ৰোগীৰ তথ্য',
  'patientName': 'ৰোগীৰ নাম',
  'enterName': 'নাম দিয়ক',
  'dateOfBirth': 'জন্ম তাৰিখ',
  'gender': 'লিংগ',
  'male': 'পুৰুষ',
  'female': 'মহিলা',
  'preferredLanguage': 'পছন্দৰ ভাষা',
  'readingPreference': 'পঢ়া/পাঠ খেলসমূহ পছন্দ',
  'dementiaStage': 'ডিমেনচিয়াৰ পৰ্যায়',
  'mild': 'পাতলীয়া',
  'moderate': 'মধ্যমীয়া',
  'severe': 'গুৰুতৰ',
  'pleaseEnterPatientName': 'অনুগ্ৰহ কৰি ৰোগীৰ নাম দিয়ক',
  'pleaseSelectDob': 'অনুগ্ৰহ কৰি জন্ম তাৰিখ বাছক',

  // Caregiver Details
  'caregiverDetails': 'সেৱাকাৰীৰ তথ্য',
  'caregiverName': 'সেৱাকাৰীৰ নাম',
  'relationshipToPatient': 'ৰোগীৰ সৈতে সম্পৰ্ক',
  'phoneNumber': 'ফোন নম্বৰ',
  'relationshipSon': 'পুত্ৰ',
  'relationshipDaughter': 'কন্যা',
  'relationshipGrandson': 'নাতি',
  'relationshipGranddaughter': 'নাতিনী',
  'relationshipSpouse': 'স্বামী/স্ত্ৰী',
  'relationshipOther': 'অন্যান্য',
  'pleaseEnterCaregiverName': 'অনুগ্ৰহ কৰি সেৱাকাৰীৰ নাম দিয়ক',
  'nameMinChars': 'নামত কমেও ৩টা আখৰ থাকিব লাগিব',
  'pleaseEnterPhone': 'অনুগ্ৰহ কৰি ফোন নম্বৰ দিয়ক',
  'validPhoneRequired': 'অনুগ্ৰহ কৰি এটা বৈধ ১০টা সংখ্যাৰ ফোন নম্বৰ দিয়ক',
  'passwordMinChars': 'পাছৱৰ্ডত কমেও ৬টা আখৰ থাকিব লাগিব',
  'passwordsDoNotMatch': 'পাছৱৰ্ড দুটা মিল খোৱা নাই',
  'registrationSuccess': 'পঞ্জীয়ন সফল হ’ল! অনুগ্ৰহ কৰি প্ৰৱেশ কৰক।',
  'registrationFailed': 'পঞ্জীয়ন ব্যৰ্থ হ’ল',

  // Dashboard / Home
  'charge': 'চাৰ্জ',
  'games': 'খেলসমূহ',
  'activities': 'কাৰ্য্যকলাপ',
  'reminders': 'সোঁৱৰণী',
  'family': 'পৰিয়াল',
  'talkToAssistant': 'সহায়কৰ সৈতে কথা পাতক',
  'voiceGuideFor': 'ইয়াৰ বাবে কণ্ঠ নিৰ্দেশনা',
  'voiceOver': 'ভইচ অভাৰ',

  // Reminders
  'todaysReminders': 'আজিৰ সোঁৱৰণী',
  'morningMedication': 'ৰাতিপুৱাৰ ঔষধ আৰু কুহুমীয়া পানী',
  'gardenStroll': 'বাগিচাত মৃদু খোজকাঢ়া',
  'nutritiousLunch': 'পুষ্টিকৰ দুপৰীয়াৰ আহাৰ আৰু ফল-মূল',
  'brainHealthMemory': 'মস্তিষ্কৰ স্বাস্থ্য স্মৃতি খেল',
  'eveningMedicine': 'গধূলিৰ ঔষধ আৰু পৰিয়ালৰ সৈতে ফোন',
  'medicineReminder': 'ঔষধ সোঁৱৰণী',
  'hydrationReminder': 'পানী খোৱা সোঁৱৰণী',
  'doctorAppointment': 'চিকিৎসকৰ সাক্ষাৎ',
  'drinkWater': 'এগিলাচ পানী খাওক',
  'takeMedicine': 'নিৰ্ধাৰিত ঔষধ খাওক',
  'completed': 'সম্পূৰ্ণ হ’ল',
  'pending': 'বাকী আছে',

  // Family Sheet
  'myFamilyAndCare': 'মোৰ পৰিয়াল আৰু সেৱা',
  'noFamilyContacts': 'এতিয়ালৈ কোনো পৰিয়ালৰ যোগাযোগ যোগ কৰা হোৱা নাই।\nসেৱাকাৰীয়ে ডেচব’ৰ্ডত যোগাযোগ যোগ কৰিব পাৰে।',
  'call': 'কল কৰক',
  'calling': 'কল কৰা হৈছে',

  // Voice Companion Sheet
  'voiceCompanion': 'কণ্ঠ সংগী',
  'voiceListeningPrompt': 'মই শুনি আছোঁ। মই আপোনাক কেনেকৈ সহায় কৰিব পাৰোঁ?',
  'voiceNews': 'আজিৰ বাতৰি শুনক',
  'voiceMusic': 'শান্ত সংগীত বজাওক',
  'voiceMedications': 'মোৰ ঔষধ পৰীক্ষা কৰক',
  'voiceCallFamily': 'মোৰ পৰিয়ালক ফোন কৰক',
  'processing': 'প্ৰক্ৰিয়াকৰণ চলি আছে',

  // Settings
  'settings': 'ছেটিংছ',
  'theme': 'থিম',
  'light': 'লাইট',
  'lightDesc': 'গাঢ় আখৰেৰে পৰিষ্কাৰ বগা পটভূমি',
  'dark': 'ডাৰ্ক',
  'darkDesc': 'কম পোহৰৰ ডাৰ্ক কন্ট্ৰাষ্ট ম’ড',
  'system': 'ছিষ্টেম',
  'systemDesc': 'ডিভাইচ ছিষ্টেম পছন্দ অনুসৰণ কৰক',
  'fontSize': 'ফন্টৰ আকাৰ',
  'small': 'সৰু',
  'smallDesc': 'মানক সংকুচিত আখৰৰ আকাৰ',
  'medium': 'মধ্যমীয়া (ডিফল্ট)',
  'mediumDesc': 'সহজে পঢ়িব পৰা সুবিধাজনক আকাৰ',
  'large': 'ডাঙৰ',
  'largeDesc': 'সহজে দেখা পোৱা ডাঙৰ আখৰ',
  'quickAccessApps': 'দ্ৰুত প্ৰৱেশ এপসমূহ',
  'language': 'ভাষা',
  'languageSubtitle': 'এপৰ ভাষা বাছক',
  'english': 'English (ইংৰাজী)',
  'hindi': 'Hindi (হিন্দী)',
  'assamese': 'Assamese (অসমীয়া)',
  'bengali': 'Bengali (বাংলা)',
  'logout': 'লগ আউট',
  'logoutConfirmation': 'আপুনি নিশ্চিতভাৱে লগ আউট কৰিব বিচাৰেনে?',

  // Games & Activities
  'memory': 'স্মৃতি',
  'attention': 'মনোযোগ',
  'executivePlanning': 'কাৰ্য্যকৰী পৰিকল্পনা',
  'perceptualMotor': 'সংবেদনশীল-চলন কৌশল',
  'memoryGames': 'স্মৃতি খেল',
  'attentionGames': 'মনোযোগ খেল',
  'executiveGames': 'কাৰ্য্যকৰী খেল',
  'perceptualMotorGames': 'সংবেদনশীল খেল',
  'beginActivity': 'কাৰ্য্যকলাপ আৰম্ভ কৰক',
  'sessionStarted': 'অধিবেশন আৰম্ভ হ’ল!',
  'startPlaying': 'খেল আৰম্ভ কৰক',

  // Games Detail & Dialogs
  'memoryHunt': 'মেম’ৰী হাণ্ট',
  'memoryHuntDesc': 'দেখুওৱা বস্তুবোৰ মনত ৰাখক',
  'pairFinder': 'জোৰা সন্ধানী',
  'pairFinderDesc': 'মিল থকা কাৰ্ডৰ জোৰা বিচাৰক',
  'pairFinderDialogDesc': 'একে ধৰণৰ কাৰ্ডৰ জোৰা মিলাই আপোনাৰ স্মৃতিশক্তি আৰু মনোযোগ বৃদ্ধি কৰক।',
  'continuousFocus': 'ধাৰাবাহিক মনোযোগ',
  'continuousFocusDesc': 'বৃত্তটো সেউজীয়া হ’লে টিপক',
  'objectFocus': 'বস্তু মনোযোগ',
  'findDifferences': 'পাৰ্থক্য বিচাৰক',
  'findDifferencesDesc': 'দুখন অনুৰূপ ছবিৰ মাজত থকা সূক্ষ্ম পাৰ্থক্যবোৰ বিচাৰি মনোযোগ বৃদ্ধি কৰক।',
  'executivePlan': 'কাৰ্য্যবাহী পৰিকল্পনা',
  'executivePlanDesc': 'দৈনন্দিন ৰুটিনৰ পৰিকল্পনা কৰক',
  'dailyTaskOrdering': 'দৈনন্দিন কামৰ ক্ৰম',
  'dailyTaskOrderingDesc': 'ৰাতিপুৱা আৰু গধূলিৰ প্ৰয়োজনীয় কামবোৰ শুদ্ধ ক্ৰমত সজাওক।',
  'activitySequencing': 'কাৰ্য্যকলাপ ক্ৰমবদ্ধতা',
  'activitySequencingDesc': 'ৰন্ধা-বঢ়া, ফুলনি আৰু দৈনিক কামবোৰ আৰম্ভণিৰ পৰা সমাপ্তিলৈকে সজাওক।',
  'shapeMatching': 'আকৃতি মিলোৱা',
  'shapeMatchingDesc': 'জ্যামিতিক আৰু প্ৰাকৃতিক আকৃতিক সঠিক স্থানত বহুৱাই হাত আৰু চকুৰ মিলন বৃদ্ধি কৰক।',
  'dragAndPlace': 'টানি আনি থওক',
  'dragAndPlaceDesc': 'বস্তুবোৰ স্পৰ্শ কৰি বাস্কেটত টানি আনি হাত-চকুৰ সমন্বয় অনুশীলন কৰক।',

  // Pair Finder Tutorial & Game Extras
  'watchBeforePlay': 'খেলাৰ আগতে চাওক',
  'howToPlay': 'কেনেকৈ খেলিব',
  'tutorialVideoNote': 'এই চুটি ভিডিঅ’টো চাওক। ভিডিঅ’ শেষ হ’লে খেলখন নিজে নিজে আৰম্ভ হ’ব।',
  'elderlyPairTip': 'মনত ৰাখিব: মিলি থকা কাৰ্ড বিচাৰিবলৈ দুখন কাৰ্ডত টিপক। সময় লৈ খেলক!',
  'startPairFinder': 'জোৰা সন্ধানী আৰম্ভ কৰক',
  'gameStartsAuto': 'টিউটৰিয়েলৰ পিছত খেলখন স্বয়ংক্ৰিয়ভাৱে আৰম্ভ হ’ব।',
  'playLevelAgain': 'পুনৰ এই স্তৰটো খেলক',
  'startNextLevel': 'পৰৱৰ্তী স্তৰ আৰম্ভ কৰক',
  'backToGames': 'খেললৈ ঘূৰি যাওক',

  // Memory Hunt UI & Flow
  'levelXOf5': 'স্তৰ {level} / ৫',
  'pleaseRememberObjects': 'অনুগ্ৰহ কৰি এই {count} টা বস্তু মনত ৰাখক',
  'pleaseRememberObjectsCarefully': 'অনুগ্ৰহ কৰি এই {count} টা বস্তু সাৱধানে মনত ৰাখক।',
  'getReady': 'প্ৰস্তুত হওক',
  'getReadyBreathe': 'প্ৰস্তুত হওক! এটা দীঘল উশাহ লওক।',
  'selectObjectsSawEarlier': 'পূৰ্বে দেখা {targetCount} টা বস্তু বাছনি কৰক ({selectedCount}/{targetCount})',
  'selectObjectsGuidance': 'পূৰ্বে দেখা {targetCount} টা বস্তু বাছনি কৰক। আপোনাৰ হাতত {hintsRemaining} টা ইঙ্গিত বাকী আছে।',
  'hint': 'ইঙ্গিত',
  'hintWithCount': 'ইঙ্গিত ({count})',
  'gotIt': 'বুজি পালোঁ',
  'hintXOf3': 'ইঙ্গিত {index} / ৩',
  'noHintsRemaining': 'কোনো ইঙ্গিত বাকী নাই',
  'allHintsUsedForLevel': 'আপুনি স্তৰ {level} ৰ বাবে ৩ টাও ইঙ্গিত ব্যৱহাৰ কৰিছে। সঠিক বস্তুবোৰ বাছনি কৰিবলৈ চেষ্টা কৰক!',
  'usedAll3Hints': 'আপুনি এই স্তৰৰ সকলো ইঙ্গিত ব্যৱহাৰ কৰিছে।',
  'tryAgainExclamation': 'পুনৰ চেষ্টা কৰক!',
  'tryAgain': 'পুনৰ চেষ্টা কৰক',
  'tryAgainPrompt': 'এইটো সম্পূৰ্ণ শুদ্ধ নহয়।\nআপোনাৰ হাতত {hintsRemaining} টা ইঙ্গিত বাকী আছে।\nসহায়ৰ বাবে এটা ইঙ্গিত ব্যৱহাৰ কৰক!',
  'tryAgainGuidance': 'পুনৰ চেষ্টা কৰক! সহায়ৰ বাবে এটা ইঙ্গিত ব্যৱহাৰ কৰক। আপোনাৰ হাতত {hintsRemaining} টা ইঙ্গিত বাকী আছে।',
  'useHintWithRemaining': 'ইঙ্গিত ব্যৱহাৰ কৰক ({count} বাকী)',
  'wellDoneExclamation': 'বৰ ভাল!',
  'youRememberedCorrectly': 'আপুনি সঠিকভাৱে মনত ৰাখিলে!',
  'wellDoneGuidance': 'বৰ ভাল! আপুনি সঠিকভাৱে মনত ৰাখিলে।',
  'foundAllLevelObjects': 'আপুনি স্তৰ {level} ৰ সকলো {count} টা বস্তু বিচাৰি পালে!',
  'foundAllFinalObjects': 'আপুনি অন্তিম স্তৰৰ সকলো ১০ টা বস্তু বিচাৰি পালে!',
  'nextLevel': 'পৰৱৰ্তী স্তৰ',
  'goodTryExclamation': 'ভাল প্ৰচেষ্টা!',
  'allHintsFinishedForLevel': 'এই স্তৰৰ বাবে ৩ টাও ইঙ্গিত সমাপ্ত হৈছে।',
  'allHintsFinishedGuidance': 'সকলো ইঙ্গিত সমাপ্ত হৈছে। শুদ্ধ বস্তুবোৰ আছিল: {answers}',
  'retryLevel': 'স্তৰটো পুনৰ খেলক',
  'continueText': 'আগলৈ যাওক',
  'congratulationsExclamation': 'অভিনন্দন!',
  'allLevelsCompleted': 'আপুনি মেম’ৰী হাণ্টৰ সকলো ৫ টা স্তৰ সম্পূৰ্ণ কৰিলে!\nআপোনাৰ স্মৃতিশক্তি অতি প্ৰখৰ আৰু সবল।',
  'allLevelsCompletedGuidance': 'অভিনন্দন! আপুনি মেম’ৰী হাণ্টৰ সকলো ৫ টা স্তৰ সম্পূৰ্ণ কৰিলে!',
  'playAgain': 'পুনৰ খেলক',
  'answers': 'উত্তৰসমূহ',
  'correctObjectsWere': 'সঠিক বস্তুবোৰ আছিল:',

  // Memory Hunt Catalog Items
  'item_apple': 'আপেল',
  'item_book': 'কিতাপ',
  'item_ball': 'বল',
  'item_cup': 'কাপ',
  'item_car': 'গাড়ী',
  'item_dog': 'কুকুৰ',
  'item_clock': 'ঘড়ী',
  'item_flower': 'ফুল',
  'item_house': 'ঘৰ',
  'item_tree': 'গছ',
  'item_sun': 'সূৰ্য্য',
  'item_star': 'তৰা',
  'item_bird': 'চৰাই',
  'item_fish': 'মাছ',
  'item_hat': 'টুপী',
  'item_key': 'চাবি',
  'item_chair': 'চকী',
  'item_boat': 'নাও',
  'item_train': 'ৰে’লগাড়ী',
  'item_umbrella': 'ছাতি',
  'item_camera': 'কেমেৰা',
  'item_guitar': 'গীটাৰ',
  'item_shoe': 'জোতা',
  'item_phone': 'ফোন',
  'item_bicycle': 'চাইকেল',
  'item_lamp': 'চাকি',

  // Memory Hunt Level Hints
  'hint_1_1': 'এটা বস্তু পাত থকা কিতাপ যাক আপুনি পঢ়ে (কিতাপ)।',
  'hint_1_2': 'এটা বস্তু স্বাস্থ্যকৰ, মিঠা ৰঙা ফল (আপেল)।',
  'hint_1_3': 'তৃতীয় বস্তুটো ঘূৰণীয়া আৰু খেলিবলৈ ব্যৱহাৰ কৰা হয় (বল)।',
  'hint_2_1': 'আকাশ আৰু সময়ৰ দুটা বস্তু চাওক: উজ্জ্বল সূৰ্য্য আৰু ঘড়ী।',
  'hint_2_2': 'প্ৰকৃতিৰ দুটা বস্তু চাওক: এটা ৰঙীন ফুল আৰু সেউজীয়া গছ।',
  'hint_2_3': 'এটা আৰামদায়ক ঘৰ য’ত মানুহ থাকে।',
  'hint_3_1': 'আকাশ আৰু পানীৰ দুটা জীৱ চাওক: চৰাই আৰু মাছ।',
  'hint_3_2': 'ৰাতিৰ আকাশত জিলিকা তৰা আৰু পানীত চলা নাও চাওক।',
  'hint_3_3': 'দৈনন্দিন বস্তু: পিন্ধিবলৈ টুপী, দুৱাৰৰ চাবি আৰু বহিবলৈ চকী।',
  'hint_4_1': 'যাতায়তৰ বাহন: ৰে’ল লাইনত চলা ৰে’লগাড়ী আৰু দুচকীয়া চাইকেল।',
  'hint_4_2': 'সংগীত আৰু ফটো: তাঁৰ থকা গীটাৰ, কেমেৰা আৰু কোঠাৰ চাকি।',
  'hint_4_3': 'দৈনন্দিন বস্তু: বৰষুণৰ ছাতি, খোজ কঢ়াৰ জোতা আৰু কথা পতা ফোন।',
  'hint_5_1': 'প্ৰকৃতি আৰু আকাশ: উজ্জ্বল সূৰ্য্য, ৰাতিৰ তৰা, সেউজীয়া গছ আৰু চৰাই।',
  'hint_5_2': 'বিনোদন আৰু ভ্ৰমণ: সুমধুৰ গীটাৰ, ফটো তোলা কেমেৰা আৰু ৰে’লগাড়ী।',
  'hint_5_3': 'নিত্য ব্যৱহাৰ্য বস্তু: সুস্বাদু আপেল, টিক-টিক কৰা ঘড়ী আৰু বৰষুণৰ ছাতি।',

  // Activities Screen
  'activitySelectVoice': 'কণ্ঠ নিৰ্দেশনা: থেৰাপী আৰম্ভ কৰিবলৈ এটা কাৰ্য্যকলাপ বাছক।',
  'reading': 'পঢ়া',
  'readingRecall': 'পঢ়া আৰু মনত পেলোৱা',
  'readingRecallDesc': 'চুটি, শান্তিদায়ক সাংস্কৃতিক গল্প উপভোগ কৰক আৰু মৃদু স্মৰণ প্ৰশ্নৰ উত্তৰ দিয়ক।',
  'familyPicture': 'পৰিয়ালৰ\nছবি',
  'familyPictureRecognition': 'পৰিয়ালৰ ছবি চিনাক্তকৰণ',
  'familyPictureRecognitionDesc': 'পৰিয়ালৰ এলবাম চাওক, মধুৰ স্মৃতিবোৰ সোঁৱৰক আৰু প্ৰিয় মুখবোৰৰ সৈতে পুনৰ সংযোগ কৰক।',
  'music': 'সংগীত',
  'musicSingingMemory': 'সংগীত আৰু গানৰ স্মৃতি',
  'musicSingingMemoryDesc': 'পৰিচিত লোকগীত আৰু গান শুনক যিয়ে নষ্টালজিক আৱেগিক স্মৃতিক জাগ্ৰত কৰে।',
  'dailyRoutineRecall': 'দৈনিক দিনচৰ্যা\nস্মৰণ',
  'dailyRoutineRecallTitle': 'দৈনিক দিনচৰ্যা স্মৰণ',
  'dailyRoutineRecallDesc': 'দৈনিক মাইলষ্টোনসমূহ মনত পেলাওক: পুৱাৰ আহাৰ, ফুলনিৰ খোজকঢ়া, ঔষধ খোৱা আৰু পৰিয়ালৰ ফোন।',

  // Reading Activity Detail
  'readingActivityTitle': 'পঢ়া কাৰ্য্যকলাপ',
  'readingActivitySubtitle': 'গল্প পঢ়ক আৰু স্মৃতি পৰীক্ষা কৰক',
  'answerQuestions': 'প্ৰশ্নৰ উত্তৰ দিয়ক',
  'backToStory': 'গল্পলৈ উভতি যাওক',
  'backToActivities': 'কাৰ্য্যকলাপলৈ উভতি যাওক',
  'previous': 'পূৰ্বৱৰ্তী',
  'nextQuestion': 'পৰৱৰ্তী প্ৰশ্ন',
  'activityCompleted': 'কাৰ্য্যকলাপ সম্পূৰ্ণ হ’ল!',
  'yourScore': 'আপোনাৰ স্ক’ৰ',
  'readingScoreCorrect': '{score} / {total} শুদ্ধ',
  'readingPerfectFeedback': 'অপূৰ্ব কাম! আজি আপোনাৰ পঢ়াৰ বুজাবুজি আৰু স্মৃতি অতি চমৎকাৰ!',
  'readingGoodFeedback': 'উত্তম প্ৰচেষ্টা! প্ৰতিদিনে পঢ়িলে স্মৃতি সতেজ আৰু সুস্থ থাকে।',
  'readStoryAgain': 'গল্প পুনৰ পঢ়ক',
  'storyNumber': 'গল্প {number}',
  'storyTitleLabel': 'গল্পৰ শিৰোনাম: {title}. {content}',
  'questionVoiceLabel': 'প্ৰশ্ন {number}: {question}',
  'story1Title': 'অসমৰ চাহ বাগিচাত এক শান্ত পুৱা',
  'story1Tag': 'অসম • সাংস্কৃতিক ঐতিহ্য',
  'story1Content': 'অসমত প্ৰতি পুৱা, যেতিয়া সেউজীয়া চাহ বাগিচাৰ ওপৰেৰে কোমল সূৰ্য্য উদয় হয়, বতাহ সতেজ পাহাৰীয়া মলয়াত ভৰি পৰে। ককাদেউতাই তেওঁৰ বাঁহৰ বাৰাণ্ডাত বহি গৰম অসম চাহৰ জুতি লৈ আকাশত চৰাইৰ কিচিমিচি গান শুনি ভাল পায়। চাহপাতবোৰ অতি যতনৰে হাতেৰে তোলা হয়, যিয়ে অঞ্চলটোৰ সকলোৰে ঘৰলৈ আনন্দ কঢ়িয়াই আনে।',
  'story1Q1': 'ককাদেউতাই পুৱা কি খাই ভাল পায়?',
  'story1Q1O1': 'গৰম অসম চাহ',
  'story1Q1O2': 'ঠাণ্ডা ডাবৰ পানী',
  'story1Q1O3': 'ফলৰ ৰস',
  'story1Q1O4': 'মচলাযুক্ত গাখীৰ',
  'story1Q2': 'ককাদেউতা পুৱা ক’ত বহে?',
  'story1Q2O1': 'পাকঘৰৰ ভিতৰত',
  'story1Q2O2': 'বাঁহৰ বাৰাণ্ডাত',
  'story1Q2O3': 'বজাৰত',
  'story1Q2O4': 'নদীৰ পাৰত',
  'story1Q3': 'অসমত চাহপাতবোৰ কেনেকৈ তোলা হয়?',
  'story1Q3O1': 'মেচিনৰ দ্বাৰা',
  'story1Q3O2': 'হাতেৰে',
  'story1Q3O3': 'আপোনা-আপুনি সৰে',
  'story1Q3O4': 'কেৱল ডাঙৰ পাচিৰে',
  'story2Title': 'আনন্দময় হৰ্ণবিল উৎসৱ',
  'story2Tag': 'নাগালেণ্ড • সাংস্কৃতিক উৎসৱ',
  'story2Content': 'নাগালেণ্ডৰ ৰঙীন হৰ্ণবিল মহোৎসৱত মানুহে পৰম্পৰাগত সাজ-পোছাক পৰিধান কৰি সংগীত, নৃত্য আৰু একতা উদযাপন কৰে। শিশুসকলে কাঠৰ ঢোলত তাল বজায় আৰু বয়োজ্যেষ্ঠসকলে বীৰত্বৰ কাহিনী কয়। চুবুৰীয়াৰ মাজত বাঁহৰ চুঙাত দিয়া ভাত আৰু সুস্বাদু খাদ্য বিতৰণ কৰা হয়।',
  'story2Q1': 'নাগালেণ্ডত কি উৎসৱ উদযাপন কৰা হৈছে?',
  'story2Q1O1': 'হৰ্ণবিল মহোৎসৱ',
  'story2Q1O2': 'বসন্ত মেলা',
  'story2Q1O3': 'কৃষি উৎসৱ',
  'story2Q1O4': 'জোনাকী উৎসৱ',
  'story2Q2': 'উৎসৱৰ সময়ত ল’ৰা-ছোৱালীয়ে কি বাদ্য বজায়?',
  'story2Q2O1': 'কাঁহৰ তাল',
  'story2Q2O2': 'কাঠৰ ঢোল',
  'story2Q2O3': 'বাঁহী',
  'story2Q2O4': 'গীটাৰ',
  'story2Q3': 'চুবুৰীয়াৰ লগত কি পৰম্পৰাগত খাদ্য ভাগ কৰা হয়?',
  'story2Q3O1': 'বাঁহৰ চুঙাত দিয়া ভাত',
  'story2Q3O2': 'ভজা ঘেঁহু',
  'story2Q3O3': 'মিঠা নুডুলছ',
  'story2Q3O4': 'আলুৰ পিঠা',

  // Music Activity Detail
  'listeningToMusic': 'সংগীত শুনা',
  'northEastFolkMelodies': 'উত্তৰ-পূৰ্বাঞ্চলৰ লোক সুৰ',
  'musicVoiceGuidance': 'সংগীত শুনিলে স্মৃতি আৰু মন শান্ত থাকে। গান শুনিবলৈ যিকোনো গানত টিপক।',
  'playingTrack': 'বাজি আছে: {title}',
  'playlistNERHeader': 'প্লেলিষ্ট (উত্তৰ-পূৰ্বাঞ্চলৰ সুৰ)',
  'track1Title': 'বিহুৰ বসন্ত তাল',
  'track1Artist': 'অসমৰ পৰম্পৰাগত লোকগীত • বাদ্যযন্ত্ৰ',
  'track2Title': 'মণিপুৰী বাঁহীৰ সুৰ',
  'track2Artist': 'ইম্ফল উপত্যকা ক্লাছিকেল • বাদ্যযন্ত্ৰ',
  'track3Title': 'খাচী পাহাৰৰ মলয়া গীত',
  'track3Artist': 'শ্বিলং লোকগীত • গান',
  'track4Title': 'মিজো নিচুকনি গীত',
  'track4Artist': 'আইজল কণ্ঠ দল • গান',

  // Family Recognition Detail
  'familyRecognition': 'পৰিয়াল চিনাক্তকৰণ',
  'familyRecognitionSubtitle': 'আপোনাৰ পৰিয়ালৰ সদস্যসকলক চিনক',
  'listenVoiceQuestion': 'কণ্ঠ প্ৰশ্ন শুনক',
  'familyVoicePrompt1': 'কোনখন ফটোত আপোনাৰ জীয়াৰী মায়া আছে, যিয়ে গুৱাহাটীৰ পৰা সতেজ চাহপাত আনে?',
  'familyVoicePrompt2': 'কোনখন ফটোত আপোনাৰ পুত্ৰ ৰাহুল আছে, যিয়ে মণিপুৰত বাঁহী বজায়?',
  'tapCorrectFamilyPhoto': 'পৰিয়ালৰ সঠিক সদস্যৰ ছবিত টিপক:',
  'voiceInput': 'কণ্ঠ ইনপুট',
  'familyVoiceInputPrompt': 'পৰিয়াল চিনাক্তকৰণ কণ্ঠ ইনপুট',
  'correctIdentification': 'শুদ্ধ চিনাক্তকৰণ!',
  'closeAttempt': 'ওচৰৰ চেষ্টা!',
  'familyCorrectFeedback': 'চমৎকাৰ! আপুনি {name} ({relationship})-ক সঠিকভাৱে চিনি পালে।',
  'familyWrongFeedback': 'সেই ছবিখন {selectedName} ({selectedRelationship})ৰ।\n\nশুদ্ধ উত্তৰ হ’ল {correctName} ({correctRelationship})।',
  'seeFinalScore': 'চূড়ান্ত স্ক’ৰ চাওক',
  'familyRecognitionComplete': 'পৰিয়াল চিনাক্তকৰণ সম্পূৰ্ণ হ’ল!',
  'familyScoreText': 'স্ক’ৰ: {score} / {total} শুদ্ধ',
  'familySummaryDesc': 'পৰিয়ালৰ মুখ চিনি পালে মধুৰ আৱেগিক স্মৃতি শক্তিশালী হয়।',
  'relationshipGrandmother': 'আইতা',

  // Emotion Recognition Detail
  'emotionRecognition': 'আৱেগ চিনাক্তকৰণ',
  'emotionRecognitionSubtitle': 'অনুভূতি আৰু মুখৰ ভাব চিনক',
  'emotionPromptHeader': 'ছবি {current} / {total}: এই ব্যক্তিজনে কেনে অনুভৱ কৰিছে?',
  'howPersonFeeling': 'এই ছবিত এই ব্যক্তিজনে কেনে অনুভৱ কৰিছে?',
  'identifyEmotionByVoice': 'কণ্ঠৰে আৱেগ কওক',
  'speakAnswer': 'উত্তৰ কওক',
  'greatJob': 'বৰ ভাল!',
  'niceTry': 'ভাল চেষ্টা!',
  'emotionCorrectFeedback': 'শুদ্ধ! এই ব্যক্তিজনে {emotion} অনুভৱ কৰিছে।\n\nদৃশ্যমান ইংগিত: {desc}',
  'emotionWrongFeedback': 'আপুনি বাছিলে {answeredEmotion}।\n\nআচলতে এই ব্যক্তিজনে {correctEmotion} অনুভৱ কৰিছে। {desc}',
  'nextPhoto': 'পৰৱৰ্তী ছবি',
  'viewScore': 'স্ক’ৰ চাওক',
  'emotionRecognitionComplete': 'আৱেগ চিনাক্তকৰণ সম্পূৰ্ণ হ’ল!',
  'emotionSummaryDesc': 'মুখৰ ভাব বুজি পালে সহমৰ্মিতা আৰু সামাজিক সম্পৰ্ক অটুট থাকে।',
  'emotionHappy': 'আনন্দিত',
  'emotionSad': 'দুখীয়া',
  'emotionCalm': 'শান্ত',
  'emotionSurprised': 'আচৰিত',
  'emotionAngry': 'খঙাল',
  'emotionHappyDesc': 'উজ্জ্বল হাঁহিৰে ভৰা চকুৰে প্ৰাণখোলা হাঁহি।',
  'emotionSadDesc': 'তললৈ চোৱা চকুৰে গহীন ভাব।',
  'emotionCalmDesc': 'শান্তিদায়ক, নম্ৰ হাঁহি।',

  // Daily Routine Recall Detail
  'dailyRoutineRecallSubtitle': 'দৈনিক অভ্যাসসমূহ ক্ৰমত সজাওক',
  'dailyRoutineInstruction': 'অনুগ্ৰহ কৰি পুৱাৰ পৰা গধূলিলৈকে কাৰ্য্যকলাপসমূহ শুদ্ধ ক্ৰমত টিপক।',
  'dailyRoutineTapOrder': 'পুৱাৰ পৰা ৰাতিলৈকে ক্ৰম অনুসৰি তলৰ কামবোৰ টিপক:',
  'resetSelection': 'বাছনি ৰিছেট কৰক',
  'checkSequence': 'ক্ৰম পৰীক্ষা কৰক',
  'selectCountOfFour': 'বাছক ({count}/4)',
  'selectFourPrompt': 'ক্ৰম সম্পূৰ্ণ কৰিবলৈ অনুগ্ৰহ কৰি আটাইকেইটা ৪টা কাৰ্য্য বাছক।',
  'routineResult': 'দৈনিক দিনচৰ্যা স্মৰণ ফলাফল',
  'routineScoreDesc': '৪টাৰ ভিতৰত {score}টা কাৰ্য্য শুদ্ধ ক্ৰমত আছে',
  'yourSequence': 'আপোনাৰ ক্ৰম:',
  'shouldBe': 'হ’ব লাগে: {title}',
  'tryShuffledAgain': 'পুনৰ সালসলনি কৰি চেষ্টা কৰক',
  'routine1Title': 'সূৰ্য্য উদয়ৰ লগে লগে সাৰ পোৱা',
  'routine2Title': 'দাঁত ঘঁহা আৰু সতেজ হোৱা',
  'routine3Title': 'পুৱাৰ আহাৰ আৰু চাহ খোৱা',
  'routine4Title': 'গধূলি ফুলনিত খোজ কঢ়া',
};

