/// Bengali (bn) translation dictionary for Seven Sisters Care
const Map<String, String> bnDict = {
  // App General
  'appTitle': 'Seven Sisters Care',
  'appSubtitle': 'এআই ভিত্তিক জ্ঞানীয় গেমিং এবং স্মৃতি সহায়তা প্ল্যাটফর্ম',
  'welcome': 'স্বাগতম',
  'save': 'সংরক্ষণ করুন',
  'cancel': 'বাতিল',
  'close': 'বন্ধ করুন',
  'back': 'ফিরে যান',
  'done': 'সম্পন্ন',
  'submit': 'জমা দিন',
  'next': 'পরবর্তী',
  'or': 'বা',
  'yes': 'হ্যাঁ',
  'no': 'না',
  'success': 'সফল',
  'error': 'ত্রুটি',
  'loading': 'লোড হচ্ছে...',
  'pleaseWait': 'অনুগ্রহ করে অপেক্ষা করুন...',

  // Authentication & Role
  'login': 'লগইন',
  'signUp': 'সাইন আপ',
  'createAccount': 'অ্যাকাউন্ট তৈরি করুন',
  'username': 'ব্যবহারকারীর নাম',
  'enterUsername': 'ব্যবহারকারীর নাম লিখুন',
  'password': 'পাসওয়ার্ড',
  'enterPassword': 'পাসওয়ার্ড লিখুন',
  'confirmPassword': 'পাসওয়ার্ড নিশ্চিত করুন',
  'dontHaveAccount': 'অ্যাকাউন্ট নেই?',
  'alreadyHaveAccount': 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
  'pleaseEnterUsername': 'অনুগ্রহ করে ব্যবহারকারীর নাম লিখুন',
  'pleaseEnterPassword': 'অনুগ্রহ করে পাসওয়ার্ড লিখুন',
  'loginSuccessful': 'লগইন সফল হয়েছে',
  'loginFailed': 'লগইন ব্যর্থ হয়েছে। তথ্য পরীক্ষা করুন।',
  'connectionError': 'সংযোগ ত্রুটি',
  'chooseYourRole': 'আপনার ভূমিকা বেছে নিন',
  'patient': 'রোগী',
  'continueAsPatient': 'রোগী হিসেবে এগিয়ে যান',
  'caregiver': 'সেবাকারী',
  'continueAsCaregiver': 'সেবাকারী হিসেবে এগিয়ে যান',

  // Patient Registration
  'setupProfile': 'প্রোফাইল সেটআপ করুন',
  'patientDetails': 'রোগীর বিবরণ',
  'patientName': 'রোগীর নাম',
  'enterName': 'নাম লিখুন',
  'dateOfBirth': 'জন্ম তারিখ',
  'gender': 'লিঙ্গ',
  'male': 'পুরুষ',
  'female': 'মহিলা',
  'preferredLanguage': 'পছন্দের ভাষা',
  'readingPreference': 'পড়া/টেক্সট গেম পছন্দ',
  'dementiaStage': 'ডিমেনশিয়ার পর্যায়',
  'mild': 'মৃদু',
  'moderate': 'মাঝারি',
  'severe': 'গুরুতর',
  'pleaseEnterPatientName': 'অনুগ্রহ করে রোগীর নাম লিখুন',
  'pleaseSelectDob': 'অনুগ্রহ করে জন্ম তারিখ নির্বাচন করুন',

  // Caregiver Details
  'caregiverDetails': 'সেবাকারীর বিবরণ',
  'caregiverName': 'সেবাকারীর নাম',
  'relationshipToPatient': 'রোগীর সাথে সম্পর্ক',
  'phoneNumber': 'ফোন নম্বর',
  'relationshipSon': 'ছেলে',
  'relationshipDaughter': 'মেয়ে',
  'relationshipGrandson': 'নাতি',
  'relationshipGranddaughter': 'নাতনি',
  'relationshipSpouse': 'স্বামী/স্ত্রী',
  'relationshipOther': 'অন্যান্য',
  'pleaseEnterCaregiverName': 'অনুগ্রহ করে সেবাকারীর নাম লিখুন',
  'nameMinChars': 'নামে কমপক্ষে ৩টি অক্ষর থাকতে হবে',
  'pleaseEnterPhone': 'অনুগ্রহ করে ফোন নম্বর লিখুন',
  'validPhoneRequired': 'অনুগ্রহ করে একটি বৈধ ১০ সংখ্যার ফোন নম্বর দিন',
  'passwordMinChars': 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে',
  'passwordsDoNotMatch': 'পাসওয়ার্ড দুটি মিলছে না',
  'registrationSuccess': 'নিবন্ধন সফল হয়েছে! অনুগ্রহ করে লগইন করুন।',
  'registrationFailed': 'নিবন্ধন ব্যর্থ হয়েছে',

  // Dashboard / Home
  'charge': 'চার্জ',
  'games': 'খেলাধুলা',
  'activities': 'ক্রিয়াকলাপ',
  'reminders': 'অনুস্মারক',
  'family': 'পরিবার',
  'talkToAssistant': 'সহকারীর সাথে কথা বলুন',
  'voiceGuideFor': 'এর জন্য ভয়েস গাইড',
  'voiceOver': 'ভয়েস ওভার',

  // Reminders
  'todaysReminders': 'আজকের অনুস্মারক',
  'morningMedication': 'সকালের ওষুধ এবং হালকা গরম জল',
  'gardenStroll': 'বাগানে মৃদু হাঁটা',
  'nutritiousLunch': 'পুষ্টিকর দুপুরের খাবার ও ফল',
  'brainHealthMemory': 'মস্তিষ্কের স্বাস্থ্য মেমরি গেম',
  'eveningMedicine': 'সন্ধ্যার ওষুধ এবং পারিবারিক কল',
  'medicineReminder': 'ওষুধ অনুস্মারক',
  'hydrationReminder': 'জল খাওয়ার অনুস্মারক',
  'doctorAppointment': 'ডাক্তারের সাক্ষাৎকার',
  'drinkWater': 'এক গ্লাস জল পান করুন',
  'takeMedicine': 'নির্ধারিত ওষুধ সেবন করুন',
  'completed': 'সম্পন্ন',
  'pending': 'অপেক্ষমান',

  // Family Sheet
  'myFamilyAndCare': 'আমার পরিবার এবং যত্ন',
  'noFamilyContacts': 'এখনও কোনো পারিবারিক যোগাযোগ যোগ করা হয়নি।\nসেবাকারী ড্যাশবোর্ডে পরিচিতি যোগ করতে পারেন।',
  'call': 'কল করুন',
  'calling': 'কল করা হচ্ছে',

  // Voice Companion Sheet
  'voiceCompanion': 'ভয়েস সঙ্গী',
  'voiceListeningPrompt': 'আমি শুনছি। আমি আপনাকে কিভাবে সাহায্য করতে পারি?',
  'voiceNews': 'আজকের খবর শুনুন',
  'voiceMusic': 'শান্ত সঙ্গীত শুনুন',
  'voiceMedications': 'আমার ওষুধ পরীক্ষা করুন',
  'voiceCallFamily': 'আমার পরিবারকে কল করুন',
  'processing': 'প্রক্রিয়াকরণ চলছে',

  // Settings
  'settings': 'সেটিংস',
  'theme': 'থিম',
  'light': 'লাইট',
  'lightDesc': 'কালো টেক্সট সহ পরিষ্কার সাদা ব্যাকগ্রাউন্ড',
  'dark': 'ডার্ক',
  'darkDesc': 'কম আলোর ডার্ক কনট্রাস্ট মোড',
  'system': 'সিস্টেম',
  'systemDesc': 'ডিভাইস সিস্টেম পছন্দ অনুসরণ করুন',
  'fontSize': 'ফন্ট সাইজ',
  'small': 'ছোট',
  'smallDesc': 'স্ট্যান্ডার্ড কমপ্যাক্ট টেক্সট সাইজ',
  'medium': 'মাঝারি (ডিফল্ট)',
  'mediumDesc': 'সহজে পড়ার জন্য উপযুক্ত সাইজ',
  'large': 'বড়',
  'largeDesc': 'সহজে দেখার জন্য বড় টেক্সট সাইজ',
  'quickAccessApps': 'দ্রুত অ্যাক্সেস অ্যাপস',
  'language': 'ভাষা',
  'languageSubtitle': 'অ্যাপের ভাষা বেছে নিন',
  'english': 'English (ইংরেজি)',
  'hindi': 'Hindi (হিন্দি)',
  'assamese': 'Assamese (অসমীয়া)',
  'bengali': 'Bengali (বাংলা)',
  'logout': 'লগআউট',
  'logoutConfirmation': 'আপনি কি নিশ্চিত যে আপনি লগআউট করতে চান?',

  // Games & Activities
  'memory': 'স্মৃতি',
  'attention': 'মনোযোগ',
  'executivePlanning': 'কার্যকরী পরিকল্পনা',
  'perceptualMotor': 'সংবেদনশীল-চলন দক্ষতা',
  'memoryGames': 'স্মৃতি খেলা',
  'attentionGames': 'মনোযোগ খেলা',
  'executiveGames': 'কার্যকরী খেলা',
  'perceptualMotorGames': 'সংবেদনশীল খেলা',
  'beginActivity': 'ক্রিয়াকলাপ শুরু করুন',
  'sessionStarted': 'সেশন শুরু হয়েছে!',
  'startPlaying': 'খেলা শুরু করুন',

  // Games Detail & Dialogs
  'memoryHunt': 'মেমরি হান্ট',
  'memoryHuntDesc': 'প্রদর্শিত আইটেমগুলি মনে রাখুন',
  'pairFinder': 'জোড়া অনুসন্ধান',
  'pairFinderDesc': 'কার্ডের মিল থাকা জোড়া খুঁজুন',
  'pairFinderDialogDesc': 'একই ধরনের কার্ডের জোড়া মিলিয়ে আপনার দৃষ্টিলব্ধ স্মৃতি ও মস্তিষ্কের ক্ষমতা বাড়ান।',
  'continuousFocus': 'ধারাবাহিক মনোযোগ',
  'continuousFocusDesc': 'বৃত্তটি সবুজ হলে ট্যাপ করুন',
  'objectFocus': 'বস্তু মনোযোগ',
  'findDifferences': 'পার্থক্য খুঁজুন',
  'findDifferencesDesc': 'দুটি ছবির মধ্যে সূক্ষ্ম পার্থক্যগুলো খুঁজে বের করে মনোযোগ বৃদ্ধি করুন।',
  'executivePlan': 'পরিকল্পনা ও সংগঠন',
  'executivePlanDesc': 'দৈনন্দিন রুটিন পরিকল্পনা করুন',
  'dailyTaskOrdering': 'দৈনন্দিন কাজের ক্রম',
  'dailyTaskOrderingDesc': 'সকাল এবং সন্ধ্যার জরুরি কাজগুলো সঠিক ক্রমে সাজান।',
  'activitySequencing': 'কার্যক্রম ক্রমবিন্যাস',
  'activitySequencingDesc': 'রান্না, বাগান ও প্রতিদিনের কাজগুলো শুরু থেকে শেষ পর্যন্ত ক্রমানুসারে সাজান।',
  'shapeMatching': 'আকৃতি মেলানো',
  'shapeMatchingDesc': 'জ্যামিতিক ও প্রাকৃতিক আকারগুলো সঠিক জায়গায় বসিয়ে হাত ও চোখের সমন্বয় বাড়ান।',
  'dragAndPlace': 'টেনে এনে রাখুন',
  'dragAndPlaceDesc': 'বস্তুগুলো টেনে ঝুড়িতে এনে হাত ও চোখের সমন্বয় অনুশীলন করুন।',

  // Pair Finder Tutorial & Game Extras
  'watchBeforePlay': 'খেলার আগে দেখুন',
  'howToPlay': 'কীভাবে খেলবেন',
  'tutorialVideoNote': 'এই সংক্ষিপ্ত ভিডিওটি দেখুন। ভিডিও শেষ হলে খেলাটি স্বয়ংক্রিয়ভাবে শুরু হবে।',
  'elderlyPairTip': 'মনে রাখুন: মিল খুঁজে পেতে দুটি কার্ডে ট্যাপ করুন। ধীরে সুস্থে খেলুন এবং আনন্দ নিন!',
  'startPairFinder': 'জোড়া অনুসন্ধান শুরু করুন',
  'gameStartsAuto': 'টিউটোরিয়ালের পর খেলাটি স্বয়ংক্রিয়ভাবে শুরু হবে।',
  'playLevelAgain': 'লেভেলটি আবার খেলুন',
  'startNextLevel': 'পরবর্তী লেভেল শুরু করুন',
  'backToGames': 'খেলায় ফিরে যান',

  // Memory Hunt UI & Flow
  'levelXOf5': 'লেভেল {level} / ৫',
  'pleaseRememberObjects': 'অনুগ্রহ করে এই {count} টি বস্তু মনে রাখুন',
  'pleaseRememberObjectsCarefully': 'অনুগ্রহ করে এই {count} টি বস্তু মনোযোগ সহকারে মনে রাখুন।',
  'getReady': 'প্রস্তুত হন',
  'getReadyBreathe': 'প্রস্তুত হন! একটি গভীর শ্বাস নিন।',
  'selectObjectsSawEarlier': 'আগে দেখা {targetCount} টি বস্তু নির্বাচন করুন ({selectedCount}/{targetCount})',
  'selectObjectsGuidance': 'আগে দেখা {targetCount} টি বস্তু নির্বাচন করুন। আপনার কাছে {hintsRemaining} টি ইঙ্গিত অবশিষ্ট আছে।',
  'hint': 'ইঙ্গিত',
  'hintWithCount': 'ইঙ্গিত ({count})',
  'gotIt': 'বুঝেছি',
  'hintXOf3': 'ইঙ্গিত {index} / ৩',
  'noHintsRemaining': 'কোনো ইঙ্গিত অবশিষ্ট নেই',
  'allHintsUsedForLevel': 'আপনি লেভেল {level}-এর সব ৩টি ইঙ্গিত ব্যবহার করেছেন। সঠিক বস্তুগুলো নির্বাচন করার চেষ্টা করুন!',
  'usedAll3Hints': 'আপনি এই লেভেলের সব ৩টি ইঙ্গিত ব্যবহার করেছেন।',
  'tryAgainExclamation': 'আবার চেষ্টা করুন!',
  'tryAgain': 'আবার চেষ্টা করুন',
  'tryAgainPrompt': 'এটি পুরোপুরি সঠিক হয়নি।\nআপনার কাছে {hintsRemaining} টি ইঙ্গিত বাকি আছে।\nসাহায্যের জন্য ইঙ্গিত ব্যবহার করুন!',
  'tryAgainGuidance': 'আবার চেষ্টা করুন! সাহায্যের জন্য ইঙ্গিত ব্যবহার করুন। আপনার কাছে {hintsRemaining} টি ইঙ্গিত বাকি আছে।',
  'useHintWithRemaining': 'ইঙ্গিত নিন ({count} বাকি)',
  'wellDoneExclamation': 'চমৎকার!',
  'youRememberedCorrectly': 'আপনি সঠিকভাবে মনে রেখেছেন!',
  'wellDoneGuidance': 'চমৎকার! আপনি সঠিকভাবে মনে রেখেছেন।',
  'foundAllLevelObjects': 'আপনি লেভেল {level}-এর সব {count} টি বস্তু খুঁজে পেয়েছেন!',
  'foundAllFinalObjects': 'আপনি শেষ লেভেলের সব ১০ টি বস্তু খুঁজে পেয়েছেন!',
  'nextLevel': 'পরবর্তী লেভেল',
  'goodTryExclamation': 'ভালো চেষ্টা!',
  'allHintsFinishedForLevel': 'এই লেভেলের সব ৩টি ইঙ্গিত শেষ হয়ে গেছে।',
  'allHintsFinishedGuidance': 'সব ইঙ্গিত শেষ হয়েছে। সঠিক বস্তুগুলো ছিল: {answers}',
  'retryLevel': 'লেভেলটি আবার চেষ্টা করুন',
  'continueText': 'এগিয়ে যান',
  'congratulationsExclamation': 'অভিনন্দন!',
  'allLevelsCompleted': 'আপনি মেমোরি হান্টের সব ৫টি লেভেল সম্পন্ন করেছেন!\nআপনার স্মৃতিশক্তি অত্যন্ত তীক্ষ্ণ ও প্রখর।',
  'allLevelsCompletedGuidance': 'অভিনন্দন! আপনি মেমোরি হান্টের সব ৫টি লেভেল সম্পন্ন করেছেন!',
  'playAgain': 'আবার খেলুন',
  'answers': 'উত্তরসমূহ',
  'correctObjectsWere': 'সঠিক বস্তুগুলো ছিল:',

  // Memory Hunt Catalog Items
  'item_apple': 'আপেল',
  'item_book': 'বই',
  'item_ball': 'বল',
  'item_cup': 'কাপ',
  'item_car': 'গাড়ি',
  'item_dog': 'কুকুর',
  'item_clock': 'ঘড়ি',
  'item_flower': 'ফুল',
  'item_house': 'বাড়ি',
  'item_tree': 'গাছ',
  'item_sun': 'সূর্য',
  'item_star': 'তারা',
  'item_bird': 'পাখি',
  'item_fish': 'মাছ',
  'item_hat': 'টুপি',
  'item_key': 'চাবি',
  'item_chair': 'চেয়ার',
  'item_boat': 'নৌকা',
  'item_train': 'ট্রেন',
  'item_umbrella': 'ছাতা',
  'item_camera': 'ক্যামেরা',
  'item_guitar': 'গিটার',
  'item_shoe': 'জুতো',
  'item_phone': 'ফোন',
  'item_bicycle': 'সাইকেল',
  'item_lamp': 'বাতি',

  // Memory Hunt Level Hints
  'hint_1_1': 'একটি বস্তু হলো পাতাযুক্ত বই যা আপনি পড়েন (বই)।',
  'hint_1_2': 'একটি বস্তু স্বাস্থ্যকর ও মিষ্টি লাল ফল (আপেল)।',
  'hint_1_3': 'তৃতীয় বস্তুটি গোল এবং বাইরে খেলার কাজে লাগে (বল)।',
  'hint_2_1': 'আকাশ ও সময়ের দুটি জিনিস দেখুন: উজ্জ্বল সূর্য এবং টিকটিক করা ঘড়ি।',
  'hint_2_2': 'প্রকৃতির দুটি জিনিস দেখুন: একটি রঙিন ফুল এবং সবুজ গাছ।',
  'hint_2_3': 'একটি আরামদায়ক বাড়ি যেখানে মানুষ বাস করে।',
  'hint_3_1': 'আকাশ ও জলের দুটি প্রাণী দেখুন: ডাকছে এমন পাখি এবং সাঁতার কাটা মাছ।',
  'hint_3_2': 'রাতের আকাশে উজ্জ্বল তারা এবং জলে ভাসা নৌকা দেখুন।',
  'hint_3_3': 'নিত্যদিনের জিনিস: পরার টুপি, দরজার চাবি এবং বসার চেয়ার।',
  'hint_4_1': 'যানবাহন: লাইনে চলা ট্রেন এবং দু চাকার সাইকেল।',
  'hint_4_2': 'গান ও ছবি: সুরের গিটার, ছবি তোলার ক্যামেরা এবং ঘরের বাতি।',
  'hint_4_3': 'দৈনন্দিন জিনিস: বৃষ্টির ছাতা, হাঁটার জুতো এবং কথা বলার ফোন।',
  'hint_5_1': 'প্রকৃতি ও আকাশ: উজ্জ্বল সূর্য, রাতের তারা, সবুজ গাছ এবং উড়ন্ত পাখি।',
  'hint_5_2': 'বিনোদন ও ভ্রমণ: মিষ্টি গিটার, ছবি তোলার ক্যামেরা এবং ট্রেন।',
  'hint_5_3': 'প্রতিদিনের দরকারি জিনিস: সুস্বাদু আপেল, ঘড়ি এবং বৃষ্টির ছাতা।',

  // Activities Screen
  'activitySelectVoice': 'ভয়েস নির্দেশাবলী: থেরাপি শুরু করতে একটি ক্রিয়াকলাপ নির্বাচন করুন।',
  'reading': 'পড়া',
  'readingRecall': 'পড়া এবং স্মরণ',
  'readingRecallDesc': 'ছোট, শান্তিদায়ক সাংস্কৃতিক গল্প উপভোগ করুন এবং মৃদু স্মরণ প্রশ্নের উত্তর দিন।',
  'familyPicture': 'পারিবারিক\nছবি',
  'familyPictureRecognition': 'পারিবারিক ছবি সনাক্তকরণ',
  'familyPictureRecognitionDesc': 'পারিবারিক অ্যালবাম দেখুন, মধুর স্মৃতিগুলো মনে করুন এবং প্রিয় মুখগুলোর সাথে পুনরায় সংযুক্ত হন।',
  'music': 'সঙ্গীত',
  'musicSingingMemory': 'সঙ্গীত এবং গানের স্মৃতি',
  'musicSingingMemoryDesc': 'পরিচিত লোক সুর এবং গান শুনুন যা নস্টালজিক মানসিক স্মৃতিকে উদ্দীপিত করে।',
  'dailyRoutineRecall': 'দৈনন্দিন রুটিন\nস্মরণ',
  'dailyRoutineRecallTitle': 'দৈনন্দিন রুটিন স্মরণ',
  'dailyRoutineRecallDesc': 'দৈনন্দিন মাইলফলকগুলো প্রতিফলিত করুন: প্রাতঃরাশ, বাগানে হাঁটা, ওষুধ খাওয়া এবং পারিবারিক কল।',

  // Reading Activity Detail
  'readingActivityTitle': 'পড়ার ক্রিয়াকলাপ',
  'readingActivitySubtitle': 'গল্প পড়ুন এবং স্মৃতি পরীক্ষা করুন',
  'answerQuestions': 'প্রশ্নের উত্তর দিন',
  'backToStory': 'গল্পে ফিরে যান',
  'backToActivities': 'ক্রিয়াকলাপে ফিরে যান',
  'previous': 'পূর্ববর্তী',
  'nextQuestion': 'পরবর্তী প্রশ্ন',
  'activityCompleted': 'ক্রিয়াকলাপ সম্পন্ন হয়েছে!',
  'yourScore': 'আপনার স্কোর',
  'readingScoreCorrect': '{score} / {total} সঠিক',
  'readingPerfectFeedback': 'দারুণ কাজ! আজ আপনার পড়ার উপলব্ধি এবং স্মৃতিশক্তি চমৎকার!',
  'readingGoodFeedback': 'দুর্দান্ত প্রচেষ্টা! প্রতিদিন পড়া স্মৃতিশক্তি তীক্ষ্ণ ও স্বাস্থ্যকর রাখে।',
  'readStoryAgain': 'গল্পটি আবার পড়ুন',
  'storyNumber': 'গল্প {number}',
  'storyTitleLabel': 'গল্পের শিরোনাম: {title}. {content}',
  'questionVoiceLabel': 'প্রশ্ন {number}: {question}',
  'story1Title': 'আসামের চা বাগানে একটি শান্ত সকাল',
  'story1Tag': 'আসাম • সাংস্কৃতিক ঐতিহ্য',
  'story1Content': 'আসামের প্রতিটি সকালে, সবুজ চা বাগানের উপর মৃদু সূর্য ওঠার সাথে সাথে বাতাস সতেজ পাহাড়ি হাওয়ায় ভরে ওঠে। দাদু তাঁর বাঁশের বারান্দায় বসে গরম আসাম চায়ে চুমুক দিতে এবং সকালের আকাশে পাখির মিষ্টি গান শুনতে ভালোবাসেন। চা পাতাগুলো যত্ন সহকারে হাতে তোলা হয়, যা এই অঞ্চলের প্রতিটি ঘরে উষ্ণতা ও আনন্দ নিয়ে আসে।',
  'story1Q1': 'দাদু সকালে কী পান করতে ভালোবাসেন?',
  'story1Q1O1': 'গরম আসাম চা',
  'story1Q1O2': 'ঠান্ডা ডাবের জল',
  'story1Q1O3': 'ফলের রস',
  'story1Q1O4': 'মশলাযুক্ত দুধ',
  'story1Q2': 'দাদু সকালে কোথায় বসেন?',
  'story1Q2O1': 'রান্নাঘরের ভেতরে',
  'story1Q2O2': 'বাঁশের বারান্দায়',
  'story1Q2O3': 'বাজারে',
  'story1Q2O4': 'নদীর তীরে',
  'story1Q3': 'আসামে কীভাবে চা পাতা তোলা হয়?',
  'story1Q3O1': 'মেশিনের সাহায্যে',
  'story1Q3O2': 'হাতে করে',
  'story1Q3O3': 'নিজে থেকেই পড়ে',
  'story1Q3O4': 'শুধু বড় ঝুড়ি দিয়ে',
  'story2Title': 'আনন্দময় হর্নবিল উৎসব',
  'story2Tag': 'নাগাল্যান্ড • সাংস্কৃতিক উৎসব',
  'story2Content': 'নাগাল্যান্ডের বর্ণিল হর্নবিল উৎসবে মানুষ ঐতিহ্যবাহী পোশাকে সঙ্গীত, নৃত্য ও ঐক্যের আনন্দ উদযাপন করে। শিশুরা কাঠের ঢোলে আনন্দঘন ছন্দ বাজায় আর প্রবীণরা পূর্বপুরুষের বীরত্বের গল্প শোনান। প্রতিবেশীদের সাথে বাঁশের চোঙায় রান্না করা ভাত ও ঐতিহ্যবাহী খাবার ভাগ করে খাওয়া হয়।',
  'story2Q1': 'নাগাল্যান্ডে কোন উৎসব উদযাপিত হচ্ছে?',
  'story2Q1O1': 'হর্নবিল উৎসব',
  'story2Q1O2': 'বসন্ত মেলা',
  'story2Q1O3': 'নবান্ন উৎসব',
  'story2Q1O4': 'জ্যোৎস্না উৎসব',
  'story2Q2': 'উৎসবের সময় শিশুরা কী বাদ্যযন্ত্র বাজায়?',
  'story2Q2O1': 'কাঁসার করতাল',
  'story2Q2O2': 'কাঠের ঢোল',
  'story2Q2O3': 'বাঁশি',
  'story2Q2O4': 'গিটার',
  'story2Q3': 'প্রতিবেশীদের সাথে কোন ঐতিহ্যবাহী খাবার ভাগ করা হয়?',
  'story2Q3O1': 'বাঁশের চোঙার ভাত',
  'story2Q3O2': 'ভাজা গম',
  'story2Q3O3': 'মিষ্টি নুডুলস',
  'story2Q3O4': 'আলুর প্যানকেক',

  // Music Activity Detail
  'listeningToMusic': 'গান শোনা',
  'northEastFolkMelodies': 'উত্তর-পূর্বের লোক সুর',
  'musicVoiceGuidance': 'গান শুনলে স্মৃতি ও মানসিক প্রশান্তি বাড়ে। শুনতে যেকোনো গানে ট্যাপ করুন।',
  'playingTrack': 'বাজছে: {title}',
  'playlistNERHeader': 'প্লেলিস্ট (উত্তর-পূর্বের সুর)',
  'track1Title': 'বিহু বসন্তের তাল',
  'track1Artist': 'আসাম ঐতিহ্যবাহী লোকসুর • বাদ্যযন্ত্র',
  'track2Title': 'মণিপুরী বাঁশির সুর',
  'track2Artist': 'ইম্ফল উপত্যকা শাস্ত্রীয় • বাদ্যযন্ত্র',
  'track3Title': 'খাসি পাহাড়ের বাতাসের গান',
  'track3Artist': 'শিলং অ্যাকোস্টিক ফোক • গান',
  'track4Title': 'মিজো ঘুমপাড়ানি গান',
  'track4Artist': 'আইজল কণ্ঠদল • গান',

  // Family Recognition Detail
  'familyRecognition': 'পরিবার সনাক্তকরণ',
  'familyRecognitionSubtitle': 'আপনার পরিবারের সদস্যদের চিনুন',
  'listenVoiceQuestion': 'ভয়েস প্রশ্ন শুনুন',
  'familyVoicePrompt1': 'কোন ছবিতে আপনার মেয়ে মায়া আছে, যে গুয়াহাটি থেকে তাজা চা পাতা আনে?',
  'familyVoicePrompt2': 'কোন ছবিতে আপনার ছেলে রাহুল আছে, যে মণিপুরে বাঁশি বাজায়?',
  'tapCorrectFamilyPhoto': 'পরিবারের সঠিক সদস্যের ছবিতে ট্যাপ করুন:',
  'voiceInput': 'ভয়েস ইনপুট',
  'familyVoiceInputPrompt': 'পরিবার সনাক্তকরণ ভয়েস ইনপুট',
  'correctIdentification': 'সঠিক সনাক্তকরণ!',
  'closeAttempt': 'কাছাকাছি চেষ্টা!',
  'familyCorrectFeedback': 'চমৎকার! আপনি {name} ({relationship})-কে সঠিকভাবে চিনতে পেরেছেন।',
  'familyWrongFeedback': 'সেই ছবিটি {selectedName} ({selectedRelationship})-এর।\n\nসঠিক উত্তর হলো {correctName} ({correctRelationship})।',
  'seeFinalScore': 'চূড়ান্ত স্কোর দেখুন',
  'familyRecognitionComplete': 'পরিবার সনাক্তকরণ সম্পন্ন হয়েছে!',
  'familyScoreText': 'স্কোর: {score} / {total} সঠিক',
  'familySummaryDesc': 'পরিবারের মুখ চিনতে পারলে মধুর মানসিক স্মৃতি শক্তিশালী হয়।',
  'relationshipGrandmother': 'ঠাকুরমা / দিদিমা',

  // Emotion Recognition Detail
  'emotionRecognition': 'অনুভূতি সনাক্তকরণ',
  'emotionRecognitionSubtitle': 'অনুভূতি ও মুখের ভাব চিনুন',
  'emotionPromptHeader': 'ছবি {current} / {total}: এই ব্যক্তি কেমন অনুভব করছেন?',
  'howPersonFeeling': 'এই ছবিতে এই ব্যক্তি কেমন অনুভব করছেন?',
  'identifyEmotionByVoice': 'কণ্ঠে অনুভূতি বলুন',
  'speakAnswer': 'উত্তর বলুন',
  'greatJob': 'দারুণ!',
  'niceTry': 'ভালো চেষ্টা!',
  'emotionCorrectFeedback': 'একদম ঠিক! এই ব্যক্তি {emotion} অনুভব করছেন।\n\nদৃশ্যমান ইঙ্গিত: {desc}',
  'emotionWrongFeedback': 'আপনি বেছেছেন {answeredEmotion}।\n\nআসলে এই ব্যক্তি {correctEmotion} অনুভব করছেন। {desc}',
  'nextPhoto': 'পরবর্তী ছবি',
  'viewScore': 'স্কোর দেখুন',
  'emotionRecognitionComplete': 'অনুভূতি সনাক্তকরণ সম্পন্ন হয়েছে!',
  'emotionSummaryDesc': 'মুখের ভাব বুঝতে পারলে সহানুভূতি এবং সামাজিক বন্ধন অটুট থাকে।',
  'emotionHappy': 'খুশি',
  'emotionSad': 'দুঃখিত',
  'emotionCalm': 'শান্ত',
  'emotionSurprised': 'বিস্মিত',
  'emotionAngry': 'রাগান্বিত',
  'emotionHappyDesc': 'উজ্জ্বল হাসিমুখ ও চকচকে চোখ।',
  'emotionSadDesc': 'নিচের দিকে তাকানো গম্ভীর মুখ।',
  'emotionCalmDesc': 'শান্তিপূর্ণ, স্নিগ্ধ হাসি।',

  // Daily Routine Recall Detail
  'dailyRoutineRecallSubtitle': 'দৈনন্দিন অভ্যাসগুলো ক্রমানুসারে সাজান',
  'dailyRoutineInstruction': 'অনুগ্রহ করে সকাল থেকে সন্ধ্যা পর্যন্ত ক্রিয়াকলাপগুলো সঠিক ক্রমে ট্যাপ করুন।',
  'dailyRoutineTapOrder': 'সকাল থেকে রাত পর্যন্ত ক্রমানুসারে নিচের কাজগুলো ট্যাপ করুন:',
  'resetSelection': 'নির্বাচন পুনরায় সেট করুন',
  'checkSequence': 'ক্রম পরীক্ষা করুন',
  'selectCountOfFour': 'নির্বাচন করুন ({count}/4)',
  'selectFourPrompt': 'ক্রম সম্পূর্ণ করতে অনুগ্রহ করে ৪টি ক্রিয়াকলাপই নির্বাচন করুন।',
  'routineResult': 'দৈনন্দিন রুটিন স্মরণ ফলাফল',
  'routineScoreDesc': '৪টির মধ্যে {score}টি ক্রিয়াকলাপ সঠিক ক্রমে রয়েছে',
  'yourSequence': 'আপনার ক্রম:',
  'shouldBe': 'হওয়া উচিত: {title}',
  'tryShuffledAgain': 'পুনরায় এলোমেলো ক্রমে চেষ্টা করুন',
  'routine1Title': 'সূর্যোদয়ে ঘুম থেকে ওঠা',
  'routine2Title': 'দাঁত মাজা ও ফ্রেশ হওয়া',
  'routine3Title': 'প্রাতঃরাশ ও চা খাওয়া',
  'routine4Title': 'সন্ধ্যায় বাগানে হাঁটা',
};

