/// English (en) translation dictionary for Seven Sisters Care
const Map<String, String> enDict = {
  // App General
  'appTitle': 'Seven Sisters Care',
  'appSubtitle': 'AI Based Cognitive Gaming and Memory Assistance Platform',
  'welcome': 'Welcome',
  'save': 'Save',
  'cancel': 'Cancel',
  'close': 'Close',
  'back': 'Back',
  'done': 'Done',
  'submit': 'Submit',
  'next': 'Next',
  'or': 'OR',
  'yes': 'Yes',
  'no': 'No',
  'success': 'Success',
  'error': 'Error',
  'loading': 'Loading...',
  'pleaseWait': 'Please wait...',

  // Authentication & Role
  'login': 'Login',
  'signUp': 'Sign Up',
  'createAccount': 'Create Account',
  'username': 'Username',
  'enterUsername': 'Enter Username',
  'password': 'Password',
  'enterPassword': 'Enter Password',
  'confirmPassword': 'Confirm Password',
  'dontHaveAccount': "Don't have an account?",
  'alreadyHaveAccount': 'Already have an account?',
  'pleaseEnterUsername': 'Please enter username',
  'pleaseEnterPassword': 'Please enter password',
  'loginSuccessful': 'Login successful',
  'loginFailed': 'Login failed. Please check your credentials.',
  'connectionError': 'Connection error',
  'chooseYourRole': 'Choose Your Role',
  'patient': 'Patient',
  'continueAsPatient': 'Continue as Patient',
  'caregiver': 'Care Giver',
  'continueAsCaregiver': 'Continue as Care Giver',

  // Patient Registration
  'setupProfile': 'Setup Profile',
  'patientDetails': 'Patient Details',
  'patientName': 'Patient Name',
  'enterName': 'Enter Name',
  'dateOfBirth': 'Date of Birth',
  'gender': 'Gender',
  'male': 'Male',
  'female': 'Female',
  'preferredLanguage': 'Preferred Language',
  'readingPreference': 'Reading/Text Games Preferred',
  'dementiaStage': 'Dementia Stage',
  'mild': 'Mild',
  'moderate': 'Moderate',
  'severe': 'Severe',
  'pleaseEnterPatientName': 'Please enter patient name',
  'pleaseSelectDob': 'Please select date of birth',

  // Caregiver Details
  'caregiverDetails': 'Caregiver Details',
  'caregiverName': 'Caregiver Name',
  'relationshipToPatient': 'Relationship To Patient',
  'phoneNumber': 'Phone Number',
  'relationshipSon': 'Son',
  'relationshipDaughter': 'Daughter',
  'relationshipGrandson': 'Grandson',
  'relationshipGranddaughter': 'Granddaughter',
  'relationshipSpouse': 'Spouse',
  'relationshipOther': 'Other',
  'pleaseEnterCaregiverName': 'Please enter caregiver name',
  'nameMinChars': 'Name must contain at least 3 characters',
  'pleaseEnterPhone': 'Please enter phone number',
  'validPhoneRequired': 'Please enter a valid 10 digit phone number',
  'passwordMinChars': 'Password must be at least 6 characters',
  'passwordsDoNotMatch': 'Passwords do not match',
  'registrationSuccess': 'Registration successful! Please login.',
  'registrationFailed': 'Registration failed',

  // Dashboard / Home
  'charge': 'Charge',
  'games': 'Games',
  'activities': 'Activities',
  'reminders': 'Remainders',
  'family': 'Family',
  'talkToAssistant': 'Talk to Assistant',
  'voiceGuideFor': 'Voice guide for',
  'voiceOver': 'Voice over',

  // Reminders
  'todaysReminders': "Today's Reminders",
  'morningMedication': 'Morning Medication & Warm Water',
  'gardenStroll': 'Gentle Garden Stroll',
  'nutritiousLunch': 'Nutritious Lunch & Fruit',
  'brainHealthMemory': 'Brain Health Memory Game',
  'eveningMedicine': 'Evening Medicine & Family Call',
  'medicineReminder': 'Medicine Reminder',
  'hydrationReminder': 'Hydration Reminder',
  'doctorAppointment': 'Doctor Appointment',
  'drinkWater': 'Drink a glass of water',
  'takeMedicine': 'Take prescribed medication',
  'completed': 'Completed',
  'pending': 'Pending',

  // Family Sheet
  'myFamilyAndCare': 'My Family & Care',
  'noFamilyContacts': 'No family contacts added yet.\nCaregiver can add contacts in Caregiver Dashboard.',
  'call': 'Call',
  'calling': 'Calling',

  // Voice Companion Sheet
  'voiceCompanion': 'Voice Companion',
  'voiceListeningPrompt': 'I am listening. How can I assist you right now?',
  'voiceNews': "Read today's news",
  'voiceMusic': 'Play soothing music',
  'voiceMedications': 'Check my medications',
  'voiceCallFamily': 'Call my family',
  'processing': 'Processing',

  // Settings
  'settings': 'Settings',
  'theme': 'Theme',
  'light': 'Light',
  'lightDesc': 'Clean white background with dark text',
  'dark': 'Dark',
  'darkDesc': 'Low-light dark contrast mode',
  'system': 'System',
  'systemDesc': 'Follow device system preferences',
  'fontSize': 'Font Size',
  'small': 'Small',
  'smallDesc': 'Standard compact text sizing',
  'medium': 'Medium (Default)',
  'mediumDesc': 'Balanced readability and comfort',
  'large': 'Large',
  'largeDesc': 'High visibility large text for easy reading',
  'quickAccessApps': 'Quick Access Apps',
  'language': 'Language',
  'languageSubtitle': 'Select app display language',
  'english': 'English',
  'hindi': 'Hindi (हिन्दी)',
  'assamese': 'Assamese (অসমীয়া)',
  'bengali': 'Bengali (বাংলা)',
  'logout': 'Logout',
  'logoutConfirmation': 'Are you sure you want to log out?',

  // Games & Activities
  'memory': 'Memory',
  'attention': 'Attention',
  'executivePlanning': 'Executive Planning',
  'perceptualMotor': 'Perceptual Motor',
  'memoryGames': 'Memory Games',
  'attentionGames': 'Attention Games',
  'executiveGames': 'Executive Games',
  'perceptualMotorGames': 'Perceptual Motor',
  'beginActivity': 'Begin Activity',
  'sessionStarted': 'Session Started!',
  'startPlaying': 'Start Playing',

  // Games Detail & Dialogs
  'memoryHunt': 'Memory Hunt',
  'memoryHuntDesc': 'Remember the items shown',
  'pairFinder': 'Pair Finder',
  'pairFinderDesc': 'Find matching pairs of cards',
  'pairFinderDialogDesc': 'Match identical card pairs to exercise visual working memory and cognitive recall.',
  'continuousFocus': 'Continuous Focus',
  'continuousFocusDesc': 'Tap when the circle turns green',
  'objectFocus': 'Object Focus',
  'findDifferences': 'Find Differences',
  'findDifferencesDesc': 'Carefully compare two similar pictures and discover subtle differences to boost sustained attention.',
  'executivePlan': 'Executive Plan',
  'executivePlanDesc': 'Plan and organize daily routines',
  'dailyTaskOrdering': 'Daily Task Ordering',
  'dailyTaskOrderingDesc': 'Arrange essential morning and evening routines in the correct logical sequence.',
  'activitySequencing': 'Activity Sequencing',
  'activitySequencingDesc': 'Organize multi-step cooking, gardening, and wellness activities from start to completion.',
  'shapeMatching': 'Shape Matching',
  'shapeMatchingDesc': 'Match geometrical and natural shapes onto outlines to enhance spatial awareness and motor agility.',
  'dragAndPlace': 'Drag & Place',
  'dragAndPlaceDesc': 'Practice hand-eye touch coordination by smoothly dragging items into designated baskets.',

  // Pair Finder Tutorial & Game Extras
  'watchBeforePlay': 'Watch before you play',
  'howToPlay': 'How to Play',
  'tutorialVideoNote': 'Watch this short tutorial. The game will start automatically when the video finishes.',
  'elderlyPairTip': 'Remember: Tap two cards to find the matching food. Take your time and enjoy!',
  'startPairFinder': 'Start Pair Finder',
  'gameStartsAuto': 'The game starts automatically after the tutorial.',
  'playLevelAgain': 'Play Level Again',
  'startNextLevel': 'Start Next Level',
  'backToGames': 'Back to Games',

  // Memory Hunt UI & Flow
  'levelXOf5': 'Level {level} of 5',
  'pleaseRememberObjects': 'Please remember these {count} objects',
  'pleaseRememberObjectsCarefully': 'Please remember these {count} objects carefully.',
  'getReady': 'Get Ready',
  'getReadyBreathe': 'Get ready! Take a deep breath.',
  'selectObjectsSawEarlier': 'Select the {targetCount} objects you saw earlier ({selectedCount}/{targetCount})',
  'selectObjectsGuidance': 'Select the {targetCount} objects you saw earlier. You have {hintsRemaining} hints remaining.',
  'hint': 'Hint',
  'hintWithCount': 'Hint ({count})',
  'gotIt': 'Got It',
  'hintXOf3': 'Hint {index} of 3',
  'noHintsRemaining': 'No Hints Remaining',
  'allHintsUsedForLevel': 'You have used all 3 hints for Level {level}. Try your best to select the matching objects!',
  'usedAll3Hints': 'You have used all 3 hints for this level.',
  'tryAgainExclamation': 'Try Again!',
  'tryAgain': 'Try Again',
  'tryAgainPrompt': 'That is not quite right.\nYou have {hintsRemaining} hint{s} remaining.\nUse a hint to help you!',
  'tryAgainGuidance': 'Try again! Use a hint to help you. You have {hintsRemaining} hints remaining.',
  'useHintWithRemaining': 'Use Hint ({count} left)',
  'wellDoneExclamation': 'Well Done!',
  'youRememberedCorrectly': 'You remembered correctly!',
  'wellDoneGuidance': 'Well done! You remembered correctly.',
  'foundAllLevelObjects': 'You found all {count} objects for Level {level}!',
  'foundAllFinalObjects': 'You found all 10 objects for the final level!',
  'nextLevel': 'Next Level',
  'goodTryExclamation': 'Good Try!',
  'allHintsFinishedForLevel': 'All 3 hints have finished for this level.',
  'allHintsFinishedGuidance': 'All hints have finished. The correct objects were: {answers}',
  'retryLevel': 'Retry Level',
  'continueText': 'Continue',
  'congratulationsExclamation': 'Congratulations!',
  'allLevelsCompleted': 'You completed all 5 levels of Memory Hunt!\nYour memory is sharp and strong.',
  'allLevelsCompletedGuidance': 'Congratulations! You completed all 5 levels of Memory Hunt!',
  'playAgain': 'Play Again',
  'answers': 'Answers',
  'correctObjectsWere': 'The correct objects were:',

  // Memory Hunt Catalog Items
  'item_apple': 'Apple',
  'item_book': 'Book',
  'item_ball': 'Ball',
  'item_cup': 'Cup',
  'item_car': 'Car',
  'item_dog': 'Dog',
  'item_clock': 'Clock',
  'item_flower': 'Flower',
  'item_house': 'House',
  'item_tree': 'Tree',
  'item_sun': 'Sun',
  'item_star': 'Star',
  'item_bird': 'Bird',
  'item_fish': 'Fish',
  'item_hat': 'Hat',
  'item_key': 'Key',
  'item_chair': 'Chair',
  'item_boat': 'Boat',
  'item_train': 'Train',
  'item_umbrella': 'Umbrella',
  'item_camera': 'Camera',
  'item_guitar': 'Guitar',
  'item_shoe': 'Shoe',
  'item_phone': 'Phone',
  'item_bicycle': 'Bicycle',
  'item_lamp': 'Lamp',

  // Memory Hunt Level Hints
  'hint_1_1': 'One of the objects is something you read with pages (Book).',
  'hint_1_2': 'One of the objects is a healthy, sweet red fruit (Apple).',
  'hint_1_3': 'The third object is round and used in outdoor games (Ball).',
  'hint_2_1': 'Look for two items in the sky and day: the bright Sun and a ticking Clock.',
  'hint_2_2': 'Look for two living nature items: a colorful Flower and a leafy green Tree.',
  'hint_2_3': 'One of the items is a cozy House where people live.',
  'hint_3_1': 'Look for creatures in sky and water: a singing Bird and swimming Fish.',
  'hint_3_2': 'Look for a glowing Star in the night sky and a sailing Boat on the water.',
  'hint_3_3': 'Look for everyday essentials: a Hat to wear, a Key for doors, and a Chair to sit.',
  'hint_4_1': 'Travel vehicles: a locomotive Train on tracks and a two-wheeled Bicycle.',
  'hint_4_2': 'Music and photos: a stringed Guitar, a Camera, and an indoor Lamp.',
  'hint_4_3': 'Daily items: an Umbrella for rain, a Shoe for walking, and a Phone for calls.',
  'hint_5_1': 'Nature and sky: shining Sun, night Star, green Tree, and soaring Bird.',
  'hint_5_2': 'Entertainment and travel: a musical Guitar, a camera to take pictures, and a Train.',
  'hint_5_3': 'Everyday essentials: a tasty Apple, a ticking Clock, and a rain Umbrella.',

  // Activities Screen
  'activitySelectVoice': 'Voice instructions: Select an activity to begin therapy.',
  'reading': 'Reading',
  'readingRecall': 'Reading & Recall',
  'readingRecallDesc': 'Enjoy short, soothing cultural stories and answer gentle recall questions.',
  'familyPicture': 'Family\nPicture',
  'familyPictureRecognition': 'Family Picture Recognition',
  'familyPictureRecognitionDesc': 'Look at fond family albums, recall cherished memories, and reconnect with beloved faces.',
  'music': 'Music',
  'musicSingingMemory': 'Music & Singing Memory',
  'musicSingingMemoryDesc': 'Listen to familiar folk tunes and songs that stimulate nostalgic emotional memory.',
  'dailyRoutineRecall': 'Daily Routine\nRecall',
  'dailyRoutineRecallTitle': 'Daily Routine Recall',
  'dailyRoutineRecallDesc': 'Reflect on daily milestones: breakfast, garden walks, medicine intake, and family calls.',
};

