/// Hindi (hi) translation dictionary for Seven Sisters Care
const Map<String, String> hiDict = {
  // App General
  'appTitle': 'Seven Sisters Care',
  'appSubtitle': 'एआई आधारित संज्ञानात्मक गेमिंग और मेमोरी सहायता प्लेटफॉर्म',
  'welcome': 'स्वागत है',
  'save': 'सहेजें',
  'cancel': 'रद्द करें',
  'close': 'बंद करें',
  'back': 'वापस',
  'done': 'पूर्ण',
  'submit': 'जमा करें',
  'next': 'आगे बढ़ें',
  'or': 'या',
  'yes': 'हाँ',
  'no': 'नहीं',
  'success': 'सफल',
  'error': 'त्रुटि',
  'loading': 'लोड हो रहा है...',
  'pleaseWait': 'कृपया प्रतीक्षा करें...',

  // Authentication & Role
  'login': 'लॉग इन',
  'signUp': 'साइन अप',
  'createAccount': 'खाता बनाएं',
  'username': 'उपयोगकर्ता नाम',
  'enterUsername': 'उपयोगकर्ता नाम दर्ज करें',
  'password': 'पासवर्ड',
  'enterPassword': 'पासवर्ड दर्ज करें',
  'confirmPassword': 'पासवर्ड की पुष्टि करें',
  'dontHaveAccount': 'खाता नहीं है?',
  'alreadyHaveAccount': 'पहले से खाता है?',
  'pleaseEnterUsername': 'कृपया उपयोगकर्ता नाम दर्ज करें',
  'pleaseEnterPassword': 'कृपया पासवर्ड दर्ज करें',
  'loginSuccessful': 'लॉग इन सफल रहा',
  'loginFailed': 'लॉग इन विफल। कृपया अपनी साख जांचें।',
  'connectionError': 'कनेक्शन त्रुटि',
  'chooseYourRole': 'अपनी भूमिका चुनें',
  'patient': 'मरीज़',
  'continueAsPatient': 'मरीज़ के रूप में जारी रखें',
  'caregiver': 'देखभालकर्ता',
  'continueAsCaregiver': 'देखभालकर्ता के रूप में जारी रखें',

  // Patient Registration
  'setupProfile': 'प्रोफ़ाइल सेटअप करें',
  'patientDetails': 'मरीज़ का विवरण',
  'patientName': 'मरीज़ का नाम',
  'enterName': 'नाम दर्ज करें',
  'dateOfBirth': 'जन्म तिथि',
  'gender': 'लिंग',
  'male': 'पुरुष',
  'female': 'महिला',
  'preferredLanguage': 'पसंदीदा भाषा',
  'readingPreference': 'पढ़ने/टेक्स्ट गेम की प्राथमिकता',
  'dementiaStage': 'डिमेंशिया का चरण',
  'mild': 'हल्का',
  'moderate': 'मध्यम',
  'severe': 'गंभीर',
  'pleaseEnterPatientName': 'कृपया मरीज़ का नाम दर्ज करें',
  'pleaseSelectDob': 'कृपया जन्म तिथि चुनें',

  // Caregiver Details
  'caregiverDetails': 'देखभालकर्ता विवरण',
  'caregiverName': 'देखभालकर्ता का नाम',
  'relationshipToPatient': 'मरीज़ से संबंध',
  'phoneNumber': 'फ़ोन नंबर',
  'relationshipSon': 'बेटा',
  'relationshipDaughter': 'बेटी',
  'relationshipGrandson': 'पोता / नाती',
  'relationshipGranddaughter': 'पोती / नातिन',
  'relationshipSpouse': 'पति/पत्नी',
  'relationshipOther': 'अन्य',
  'pleaseEnterCaregiverName': 'कृपया देखभालकर्ता का नाम दर्ज करें',
  'nameMinChars': 'नाम में कम से कम 3 अक्षर होने चाहिए',
  'pleaseEnterPhone': 'कृपया फ़ोन नंबर दर्ज करें',
  'validPhoneRequired': 'कृपया मान्य 10 अंकों का फ़ोन नंबर दर्ज करें',
  'passwordMinChars': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए',
  'passwordsDoNotMatch': 'पासवर्ड मेल नहीं खाते',
  'registrationSuccess': 'पंजीकरण सफल! कृपया लॉग इन करें।',
  'registrationFailed': 'पंजीकरण विफल',

  // Dashboard / Home
  'charge': 'चार्ज',
  'games': 'खेल',
  'activities': 'गतिविधियाँ',
  'reminders': 'अनुस्मारक',
  'family': 'परिवार',
  'talkToAssistant': 'सहायक से बात करें',
  'voiceGuideFor': 'इसके लिए वॉयस गाइड',
  'voiceOver': 'वॉयस ओवर',

  // Reminders
  'todaysReminders': 'आज के अनुस्मारक',
  'morningMedication': 'सुबह की दवा और गुनगुना पानी',
  'gardenStroll': 'बगीचे में हल्की सैर',
  'nutritiousLunch': 'पौष्टिक दोपहर का भोजन और फल',
  'brainHealthMemory': 'मस्तिष्क स्वास्थ्य मेमोरी गेम',
  'eveningMedicine': 'शाम की दवा और पारिवारिक कॉल',
  'medicineReminder': 'दवा अनुस्मारक',
  'hydrationReminder': 'जल अनुस्मारक',
  'doctorAppointment': 'डॉक्टर अपॉइंटमेंट',
  'drinkWater': 'एक गिलास पानी पिएं',
  'takeMedicine': 'निर्धारित दवा लें',
  'completed': 'पूर्ण',
  'pending': 'लंबित',

  // Family Sheet
  'myFamilyAndCare': 'मेरा परिवार और देखभाल',
  'noFamilyContacts': 'अभी तक कोई पारिवारिक संपर्क नहीं जोड़ा गया।\nदेखभालकर्ता डैशबोर्ड में संपर्क जोड़ सकते हैं।',
  'call': 'कॉल करें',
  'calling': 'कॉल किया जा रहा है',

  // Voice Companion Sheet
  'voiceCompanion': 'वॉयस साथी',
  'voiceListeningPrompt': 'मैं सुन रहा हूँ। मैं आपकी किस प्रकार सहायता कर सकता हूँ?',
  'voiceNews': 'आज के समाचार पढ़ें',
  'voiceMusic': 'शांत संगीत बजाएं',
  'voiceMedications': 'मेरी दवाएं जांचें',
  'voiceCallFamily': 'मेरे परिवार को कॉल करें',
  'processing': 'प्रक्रिया जारी है',

  // Settings
  'settings': 'सेटिंग्स',
  'theme': 'थीम',
  'light': 'लाइट',
  'lightDesc': 'काले टेक्स्ट के साथ साफ सफ़ेद पृष्ठभूमि',
  'dark': 'डार्क',
  'darkDesc': 'कम रोशनी वाला डार्क कंट्रास्ट मोड',
  'system': 'सिस्टम',
  'systemDesc': 'डिवाइस सिस्टम प्राथमिकताओं का पालन करें',
  'fontSize': 'फ़ॉन्ट आकार',
  'small': 'छोटा',
  'smallDesc': 'मानक कॉम्पैक्ट टेक्स्ट आकार',
  'medium': 'मध्यम (डिफ़ॉल्ट)',
  'mediumDesc': 'संतुलित पठनीयता और आराम',
  'large': 'बड़ा',
  'largeDesc': 'आसानी से पढ़ने के लिए बड़ा टेक्स्ट',
  'quickAccessApps': 'त्वरित पहुंच ऐप्स',
  'language': 'भाषा',
  'languageSubtitle': 'ऐप की भाषा चुनें',
  'english': 'English (अंग्रेज़ी)',
  'hindi': 'Hindi (हिन्दी)',
  'assamese': 'Assamese (অসমীয়া)',
  'bengali': 'Bengali (বাংলা)',
  'logout': 'लॉग आउट',
  'logoutConfirmation': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',

  // Games & Activities
  'memory': 'स्मृति',
  'attention': 'एकाग्रता',
  'executivePlanning': 'कार्यकारी योजना',
  'perceptualMotor': 'संवेदी-प्रेरक कौशल',
  'memoryGames': 'स्मृति खेल',
  'attentionGames': 'एकाग्रता खेल',
  'executiveGames': 'कार्यकारी खेल',
  'perceptualMotorGames': 'संवेदी-प्रेरक खेल',
  'beginActivity': 'गतिविधि शुरू करें',
  'sessionStarted': 'सत्र शुरू हुआ!',
  'startPlaying': 'खेल शुरू करें',

  // Games Detail & Dialogs
  'memoryHunt': 'मेमोरी हंट',
  'memoryHuntDesc': 'दिखाई गई वस्तुओं को याद रखें',
  'pairFinder': 'जोड़ी खोजक',
  'pairFinderDesc': 'कार्ड के मिलान वाले जोड़े खोजें',
  'pairFinderDialogDesc': 'समान कार्डों के जोड़े मिलाकर अपनी दृश्य स्मृति और मानसिक क्षमता को मजबूत करें।',
  'continuousFocus': 'निरंतर ध्यान',
  'continuousFocusDesc': 'जब चक्र हरा हो जाए तो टैप करें',
  'objectFocus': 'वस्तु ध्यान',
  'findDifferences': 'अंतर पहचानें',
  'findDifferencesDesc': 'दो चित्रों की तुलना करें और ध्यान केंद्रित करने के लिए सूक्ष्म अंतर खोजें।',
  'executivePlan': 'योजना और संगठन',
  'executivePlanDesc': 'दैनिक दिनचर्या की योजना बनाएं',
  'dailyTaskOrdering': 'दैनिक कार्य क्रम',
  'dailyTaskOrderingDesc': 'सुबह और शाम की आवश्यक दिनचर्या को सही क्रम में व्यवस्थित करें।',
  'activitySequencing': 'गतिविधि क्रमबद्धता',
  'activitySequencingDesc': 'रसोई, बागवानी और दैनिक कार्यों को शुरुआत से अंत तक सही क्रम में लगाएं।',
  'shapeMatching': 'आकार मिलान',
  'shapeMatchingDesc': 'आकारों को उनकी रूपरेखा से मिलाकर अपनी गतिशीलता और समझ को बढ़ाएं।',
  'dragAndPlace': 'खींचें और रखें',
  'dragAndPlaceDesc': 'वस्तुओं को छूकर टोकरी में खींचें और हाथ-आंख के समन्वय का अभ्यास करें।',

  // Pair Finder Tutorial & Game Extras
  'watchBeforePlay': 'खेलने से पहले देखें',
  'howToPlay': 'कैसे खेलें',
  'tutorialVideoNote': 'यह छोटा वीडियो देखें। वीडियो समाप्त होने पर खेल अपने आप शुरू हो जाएगा।',
  'elderlyPairTip': 'याद रखें: मिलते-जुलते कार्ड खोजने के लिए दो कार्डों पर टैप करें। आराम से खेलें!',
  'startPairFinder': 'जोड़ी खोजक शुरू करें',
  'gameStartsAuto': 'ट्यूटोरियल के बाद खेल अपने आप शुरू हो जाएगा।',
  'playLevelAgain': 'स्तर दोबारा खेलें',
  'startNextLevel': 'अगला स्तर शुरू करें',
  'backToGames': 'खेलों पर वापस जाएं',

  // Memory Hunt UI & Flow
  'levelXOf5': 'स्तर {level} / 5',
  'pleaseRememberObjects': 'कृपया इन {count} वस्तुओं को याद रखें',
  'pleaseRememberObjectsCarefully': 'कृपया इन {count} वस्तुओं को ध्यान से याद रखें।',
  'getReady': 'तैयार हो जाइए',
  'getReadyBreathe': 'तैयार हो जाइए! एक गहरी सांस लें।',
  'selectObjectsSawEarlier': 'पहले देखी गई {targetCount} वस्तुओं को चुनें ({selectedCount}/{targetCount})',
  'selectObjectsGuidance': 'पहले देखी गई {targetCount} वस्तुओं को चुनें। आपके पास {hintsRemaining} संकेत शेष हैं।',
  'hint': 'संकेत',
  'hintWithCount': 'संकेत ({count})',
  'gotIt': 'समझ गया',
  'hintXOf3': 'संकेत {index} / 3',
  'noHintsRemaining': 'कोई संकेत शेष नहीं',
  'allHintsUsedForLevel': 'आपने स्तर {level} के सभी 3 संकेत उपयोग कर लिए हैं। सही वस्तुओं को चुनने का प्रयास करें!',
  'usedAll3Hints': 'आपने इस स्तर के सभी 3 संकेत उपयोग कर लिए हैं।',
  'tryAgainExclamation': 'पुनः प्रयास करें!',
  'tryAgain': 'पुनः प्रयास करें',
  'tryAgainPrompt': 'यह पूरी तरह सही नहीं है।\nआपके पास {hintsRemaining} संकेत शेष हैं।\nमदद के लिए संकेत का उपयोग करें!',
  'tryAgainGuidance': 'पुनः प्रयास करें! मदद के लिए संकेत का उपयोग करें। आपके पास {hintsRemaining} संकेत शेष हैं।',
  'useHintWithRemaining': 'संकेत लें ({count} शेष)',
  'wellDoneExclamation': 'बहुत बढ़िया!',
  'youRememberedCorrectly': 'आपने बिल्कुल सही याद रखा!',
  'wellDoneGuidance': 'बहुत बढ़िया! आपने बिल्कुल सही याद रखा।',
  'foundAllLevelObjects': 'आपने स्तर {level} की सभी {count} वस्तुएं ढूंढ लीं!',
  'foundAllFinalObjects': 'आपने अंतिम स्तर की सभी 10 वस्तुएं ढूंढ लीं!',
  'nextLevel': 'अगला स्तर',
  'goodTryExclamation': 'अच्छा प्रयास!',
  'allHintsFinishedForLevel': 'इस स्तर के सभी 3 संकेत समाप्त हो चुके हैं।',
  'allHintsFinishedGuidance': 'सभी संकेत समाप्त हो गए हैं। सही वस्तुएं थीं: {answers}',
  'retryLevel': 'स्तर दोबारा खेलें',
  'continueText': 'आगे बढ़ें',
  'congratulationsExclamation': 'बधाई हो!',
  'allLevelsCompleted': 'आपने मेमोरी हंट के सभी 5 स्तर पूरे कर लिए हैं!\nआपकी याददाश्त बहुत तेज और मजबूत है।',
  'allLevelsCompletedGuidance': 'बधाई हो! आपने मेमोरी हंट के सभी 5 स्तर पूरे कर लिए हैं!',
  'playAgain': 'फिर से खेलें',
  'answers': 'उत्तर',
  'correctObjectsWere': 'सही वस्तुएं थीं:',

  // Memory Hunt Catalog Items
  'item_apple': 'सेब',
  'item_book': 'किताब',
  'item_ball': 'गेंद',
  'item_cup': 'कप',
  'item_car': 'गाड़ी',
  'item_dog': 'कुत्ता',
  'item_clock': 'घड़ी',
  'item_flower': 'फूल',
  'item_house': 'घर',
  'item_tree': 'पेड़',
  'item_sun': 'सूरज',
  'item_star': 'तारा',
  'item_bird': 'चिड़िया',
  'item_fish': 'मछली',
  'item_hat': 'टोपी',
  'item_key': 'चाबी',
  'item_chair': 'कुर्सी',
  'item_boat': 'नाव',
  'item_train': 'रेलगाड़ी',
  'item_umbrella': 'छाता',
  'item_camera': 'कैमरा',
  'item_guitar': 'गिटार',
  'item_shoe': 'जूता',
  'item_phone': 'फ़ोन',
  'item_bicycle': 'साइकिल',
  'item_lamp': 'दीपक',

  // Memory Hunt Level Hints
  'hint_1_1': 'एक वस्तु पन्नों वाली किताब है जिसे आप पढ़ते हैं (किताब)।',
  'hint_1_2': 'एक वस्तु स्वस्थ और मीठा लाल फल है (सेब)।',
  'hint_1_3': 'तीसरी वस्तु गोल है और बाहर खेलने में काम आती है (गेंद)।',
  'hint_2_1': 'आसमान और समय की दो वस्तुएं देखें: चमकता सूरज और टिक-टिक करती घड़ी।',
  'hint_2_2': 'प्रकृति की दो वस्तुएं देखें: एक सुंदर फूल और हरा-भरा पेड़।',
  'hint_2_3': 'एक आरामदायक घर है जहां लोग रहते हैं।',
  'hint_3_1': 'आकाश और पानी के जीव देखें: चहकती चिड़िया और तैरती मछली।',
  'hint_3_2': 'रात के आकाश में चमकता तारा और पानी पर चलती नाव देखें।',
  'hint_3_3': 'दैनिक उपयोग की वस्तुएं: पहनने की टोपी, दरवाज़े की चाबी और बैठने की कुर्सी।',
  'hint_4_1': 'सवारी के साधन: पटरी पर दौड़ती रेलगाड़ी और दो पहियों वाली साइकिल।',
  'hint_4_2': 'संगीत और तस्वीरें: तारों वाला गिटार, कैमरा और कमरे का दीपक।',
  'hint_4_3': 'दैनिक वस्तुएं: बारिश के लिए छाता, चलने के लिए जूता और बात करने के लिए फ़ोन।',
  'hint_5_1': 'प्रकृति और आकाश: चमकता सूरज, रात का तारा, हरा पेड़ और उड़ती चिड़िया।',
  'hint_5_2': 'मनोरंजन और यात्रा: सुरमयी गिटार, तस्वीर खींचने का कैमरा और रेलगाड़ी।',
  'hint_5_3': 'रोज़मर्रा की चीज़ें: स्वादिष्ट सेब, टिक-टिक करती घड़ी और बारिश का छाता।',

  // Activities Screen
  'activitySelectVoice': 'वॉयस निर्देश: थेरेपी शुरू करने के लिए कोई गतिविधि चुनें।',
  'reading': 'पठन',
  'readingRecall': 'पठन और स्मरण',
  'readingRecallDesc': 'छोटी, सुखद सांस्कृतिक कहानियों का आनंद लें और सौम्य स्मरण प्रश्नों के उत्तर दें।',
  'familyPicture': 'पारिवारिक\nतस्वीर',
  'familyPictureRecognition': 'पारिवारिक तस्वीर पहचान',
  'familyPictureRecognitionDesc': 'पारिवारिक एल्बम देखें, पुरानी यादों को ताज़ा करें और प्रियजनों से जुड़ें।',
  'music': 'संगीत',
  'musicSingingMemory': 'संगीत और गायन स्मृति',
  'musicSingingMemoryDesc': 'परिचित लोक धुनों और गीतों को सुनें जो भावनात्मक यादों को ताज़ा करते हैं।',
  'dailyRoutineRecall': 'दैनिक दिनचर्या\nस्मरण',
  'dailyRoutineRecallTitle': 'दैनिक दिनचर्या स्मरण',
  'dailyRoutineRecallDesc': 'दैनिक कार्यों को याद करें: नाश्ता, बगीचे की सैर, दवा लेना और पारिवारिक बातचीत।',

  // Reading Activity Detail
  'readingActivityTitle': 'पठन गतिविधि',
  'readingActivitySubtitle': 'कहानी पढ़ें और याददाश्त परखें',
  'answerQuestions': 'प्रश्नों के उत्तर दें',
  'backToStory': 'कहानी पर वापस जाएं',
  'backToActivities': 'गतिविधियों पर वापस जाएं',
  'previous': 'पिछला',
  'nextQuestion': 'अगला प्रश्न',
  'activityCompleted': 'गतिविधि पूर्ण हुई!',
  'yourScore': 'आपका स्कोर',
  'readingScoreCorrect': '{score} / {total} सही',
  'readingPerfectFeedback': 'अद्भुत काम! आपकी पढ़ने की समझ और याददाश्त आज उत्कृष्ट है!',
  'readingGoodFeedback': 'शानदार प्रयास! रोज़ाना पढ़ने से याददाश्त तेज़ और स्वस्थ रहती है।',
  'readStoryAgain': 'कहानी दोबारा पढ़ें',
  'storyNumber': 'कहानी {number}',
  'storyTitleLabel': 'कहानी का शीर्षक: {title}. {content}',
  'questionVoiceLabel': 'प्रश्न {number}: {question}',
  'story1Title': 'असम के चाय बागानों में एक शांत सुबह',
  'story1Tag': 'असम • सांस्कृतिक धरोहर',
  'story1Content': 'असम में हर सुबह, जब हरे-भरे चाय बागानों पर सूरज की किरणें पड़ती हैं, तो हवा में ताज़ी पहाड़ी महक घुल जाती है। दादाजी को अपने बांस के बरामदे में बैठकर गरम असम चाय की चुस्की लेना और सुबह के आकाश में चिड़ियों की चहचहाहट सुनना बहुत पसंद है। चाय की पत्तियां हाथों से चुनी जाती हैं, जो पूरे क्षेत्र के परिवारों में अपनापन और मिठास लाती हैं।',
  'story1Q1': 'दादाजी सुबह क्या पीना पसंद करते हैं?',
  'story1Q1O1': 'गरम असम चाय',
  'story1Q1O2': 'ठंडा नारियल पानी',
  'story1Q1O3': 'फलों का रस',
  'story1Q1O4': 'मसालेदार दूध',
  'story1Q2': 'दादाजी सुबह कहाँ बैठते हैं?',
  'story1Q2O1': 'रसोई के अंदर',
  'story1Q2O2': 'अपने बांस के बरामदे में',
  'story1Q2O3': 'बाज़ार में',
  'story1Q2O4': 'नदी किनारे',
  'story1Q3': 'असम में चाय की पत्तियां कैसे चुनी जाती हैं?',
  'story1Q3O1': 'मशीन द्वारा',
  'story1Q3O2': 'हाथों द्वारा',
  'story1Q3O3': 'वे खुद गिरती हैं',
  'story1Q3O4': 'केवल बड़ी टोकरियों से',
  'story2Title': 'हॉर्नबिल का आनंदमय उत्सव',
  'story2Tag': 'नागालैंड • सांस्कृतिक उत्सव',
  'story2Content': 'नागालैंड के रंग-बिरंगे हॉर्नबिल महोत्सव में लोग पारंपरिक परिधान पहनकर संगीत, नृत्य और एकता का उत्सव मनाते हैं। बच्चे लकड़ी के ढोलों पर थाप लगाते हैं जबकि बुजुर्ग पूर्वजों की कहानियां सुनाते हैं। पड़ोसी आपस में बांस में पके चावल और पारंपरिक पकवान बांटते हैं।',
  'story2Q1': 'नागालैंड में कौन सा उत्सव मनाया जा रहा है?',
  'story2Q1O1': 'हॉर्नबिल महोत्सव',
  'story2Q1O2': 'वसंत मेला',
  'story2Q1O3': 'फसल उत्सव',
  'story2Q1O4': 'चांदनी उत्सव',
  'story2Q2': 'उत्सव के दौरान बच्चे कौन सा वाद्य यंत्र बजाते हैं?',
  'story2Q2O1': 'पीतल की झांझ',
  'story2Q2O2': 'लकड़ी के ढोल',
  'story2Q2O3': 'बांसुरी',
  'story2Q2O4': 'गिटार',
  'story2Q3': 'पड़ोसियों के साथ कौन सा पारंपरिक पकवान बांटा जाता है?',
  'story2Q3O1': 'बांस में पके चावल',
  'story2Q3O2': 'तले हुए गेहूं',
  'story2Q3O3': 'मीठे नूडल्स',
  'story2Q3O4': 'आलू के पैनकेक',

  // Music Activity Detail
  'listeningToMusic': 'संगीत सुनना',
  'northEastFolkMelodies': 'पूर्वोत्तर की लोक धुनें',
  'musicVoiceGuidance': 'संगीत सुनने से याददाश्त और मानसिक शांति मिलती है। सुनने के लिए किसी भी गीत पर टैप करें।',
  'playingTrack': 'बज रहा है: {title}',
  'playlistNERHeader': 'प्लेलिस्ट (पूर्वोत्तर धुनें)',
  'track1Title': 'बिहू वसंत ताल',
  'track1Artist': 'असम पारंपरिक लोक • वाद्य संगीत',
  'track2Title': 'मणिपुरी बांसुरी की धुन',
  'track2Artist': 'इम्फाल घाटी शास्त्रीय • वाद्य संगीत',
  'track3Title': 'खासी हिल्स हवा का गीत',
  'track3Artist': 'शिलांग ध्वनिक लोक • गीत',
  'track4Title': 'मिज़ो लोरी',
  'track4Artist': 'आइज़ोल गायक मंडली • गीत',

  // Family Recognition Detail
  'familyRecognition': 'पारिवारिक पहचान',
  'familyRecognitionSubtitle': 'अपने परिवार के सदस्यों को पहचानें',
  'listenVoiceQuestion': 'वॉयस प्रश्न सुनें',
  'familyVoicePrompt1': 'कौन सी तस्वीर आपकी बेटी माया की है, जो गुवाहाटी से ताज़ा चाय पत्तियां लाती है?',
  'familyVoicePrompt2': 'कौन सी तस्वीर आपके बेटे राहुल की है, जो मणिपुर में बांसुरी बजाता है?',
  'tapCorrectFamilyPhoto': 'परिवार के सही सदस्य की तस्वीर पर टैप करें:',
  'voiceInput': 'वॉयस इनपुट',
  'familyVoiceInputPrompt': 'पारिवारिक पहचान वॉयस इनपुट',
  'correctIdentification': 'सही पहचान!',
  'closeAttempt': 'निकटतम प्रयास!',
  'familyCorrectFeedback': 'बहुत बढ़िया! आपने {name} ({relationship}) को सही पहचाना।',
  'familyWrongFeedback': 'वह तस्वीर {selectedName} ({selectedRelationship}) की है।\n\nसही उत्तर है {correctName} ({correctRelationship})।',
  'seeFinalScore': 'अंतिम स्कोर देखें',
  'familyRecognitionComplete': 'पारिवारिक पहचान पूर्ण हुई!',
  'familyScoreText': 'स्कोर: {score} / {total} सही',
  'familySummaryDesc': 'परिवार के चेहरों को पहचानने से सुखद भावनात्मक यादें मज़बूत होती हैं।',
  'relationshipGrandmother': 'दादी / नानी',

  // Emotion Recognition Detail
  'emotionRecognition': 'भावना पहचान',
  'emotionRecognitionSubtitle': 'भाव और अभिव्यक्ति पहचानें',
  'emotionPromptHeader': 'तस्वीर {current} / {total}: यह व्यक्ति कैसा महसूस कर रहा है?',
  'howPersonFeeling': 'इस तस्वीर में यह व्यक्ति कैसा महसूस कर रहा है?',
  'identifyEmotionByVoice': 'आवाज़ से भावना बताएं',
  'speakAnswer': 'उत्तर बोलें',
  'greatJob': 'बहुत बढ़िया!',
  'niceTry': 'अच्छा प्रयास!',
  'emotionCorrectFeedback': 'बिल्कुल सही! यह व्यक्ति {emotion} महसूस कर रहा है।\n\nदृश्य संकेत: {desc}',
  'emotionWrongFeedback': 'आपने चुना {answeredEmotion}।\n\nवास्तव में यह व्यक्ति {correctEmotion} महसूस कर रहा है। {desc}',
  'nextPhoto': 'अगली तस्वीर',
  'viewScore': 'स्कोर देखें',
  'emotionRecognitionComplete': 'भावना पहचान पूर्ण हुई!',
  'emotionSummaryDesc': 'चेहरे के भावों को समझने से सहानुभूति और सामाजिक संबंध बने रहते हैं।',
  'emotionHappy': 'खुश',
  'emotionSad': 'उदास',
  'emotionCalm': 'शांत',
  'emotionSurprised': 'आश्चर्यचकित',
  'emotionAngry': 'क्रोधित',
  'emotionHappyDesc': 'उज्ज्वल मुस्कुराती आँखों के साथ गर्मजोशी से मुस्कुराते हुए।',
  'emotionSadDesc': 'नीचे झुकी आँखों के साथ गंभीर भाव।',
  'emotionCalmDesc': 'शांतिपूर्ण, सौम्य मुस्कान।',

  // Daily Routine Recall Detail
  'dailyRoutineRecallSubtitle': 'दैनिक आदतों को सही क्रम में लगाएं',
  'dailyRoutineInstruction': 'कृपया सुबह से शाम तक की दैनिक गतिविधियों को सही क्रम में टैप करें।',
  'dailyRoutineTapOrder': 'सुबह से रात तक की गतिविधियों को नीचे क्रम से टैप करें:',
  'resetSelection': 'चयन रीसेट करें',
  'checkSequence': 'क्रम जांचें',
  'selectCountOfFour': 'चयन करें ({count}/4)',
  'selectFourPrompt': 'क्रम पूरा करने के लिए कृपया सभी 4 गतिविधियों का चयन करें।',
  'routineResult': 'दैनिक दिनचर्या स्मरण परिणाम',
  'routineScoreDesc': '4 में से {score} गतिविधियां सही क्रम में हैं',
  'yourSequence': 'आपका क्रम:',
  'shouldBe': 'होना चाहिए: {title}',
  'tryShuffledAgain': 'बदले हुए क्रम में पुनः प्रयास करें',
  'routine1Title': 'सूर्योदय पर जागना',
  'routine2Title': 'दांत साफ करना और तरोताज़ा होना',
  'routine3Title': 'नाश्ता और चाय लेना',
  'routine4Title': 'शाम को बगीचे में टहलना',
};

