/// Hindi (hi) translation dictionary for Seven Sisters Care
const Map<String, String> hiDict = {
  // App General
  'appTitle': 'Seven Sisters Care',
  'appSubtitle': 'एआई आधारित संज्ञानात्मक गेमिंग और मेमोरी सहायता प्लेटफॉर्म',
  'welcome': 'स्वागत है',
  'save': 'सहेजें',
  'cancel': 'रद्द करें',
  'close': 'बंद करें',
  'back': 'वापस',
  'done': 'पूर्ण',
  'submit': 'जमा करें',
  'next': 'आगे बढ़ें',
  'or': 'या',
  'yes': 'हाँ',
  'no': 'नहीं',
  'success': 'सफल',
  'error': 'त्रुटि',
  'loading': 'लोड हो रहा है...',
  'pleaseWait': 'कृपया प्रतीक्षा करें...',

  // Authentication & Role
  'login': 'लॉग इन',
  'signUp': 'साइन अप',
  'createAccount': 'खाता बनाएं',
  'username': 'उपयोगकर्ता नाम',
  'enterUsername': 'उपयोगकर्ता नाम दर्ज करें',
  'password': 'पासवर्ड',
  'enterPassword': 'पासवर्ड दर्ज करें',
  'confirmPassword': 'पासवर्ड की पुष्टि करें',
  'dontHaveAccount': 'खाता नहीं है?',
  'alreadyHaveAccount': 'पहले से खाता है?',
  'pleaseEnterUsername': 'कृपया उपयोगकर्ता नाम दर्ज करें',
  'pleaseEnterPassword': 'कृपया पासवर्ड दर्ज करें',
  'loginSuccessful': 'लॉग इन सफल रहा',
  'loginFailed': 'लॉग इन विफल। कृपया अपनी साख जांचें।',
  'connectionError': 'कनेक्शन त्रुटि',
  'chooseYourRole': 'अपनी भूमिका चुनें',
  'patient': 'मरीज़',
  'continueAsPatient': 'मरीज़ के रूप में जारी रखें',
  'caregiver': 'देखभालकर्ता',
  'continueAsCaregiver': 'देखभालकर्ता के रूप में जारी रखें',

  // Patient Registration
  'setupProfile': 'प्रोफ़ाइल सेटअप करें',
  'patientDetails': 'मरीज़ का विवरण',
  'patientName': 'मरीज़ का नाम',
  'enterName': 'नाम दर्ज करें',
  'dateOfBirth': 'जन्म तिथि',
  'gender': 'लिंग',
  'male': 'पुरुष',
  'female': 'महिला',
  'preferredLanguage': 'पसंदीदा भाषा',
  'readingPreference': 'पढ़ने/टेक्स्ट गेम की प्राथमिकता',
  'dementiaStage': 'डिमेंशिया का चरण',
  'mild': 'हल्का',
  'moderate': 'मध्यम',
  'severe': 'गंभीर',
  'pleaseEnterPatientName': 'कृपया मरीज़ का नाम दर्ज करें',
  'pleaseSelectDob': 'कृपया जन्म तिथि चुनें',

  // Caregiver Details
  'caregiverDetails': 'देखभालकर्ता विवरण',
  'caregiverName': 'देखभालकर्ता का नाम',
  'relationshipToPatient': 'मरीज़ से संबंध',
  'phoneNumber': 'फ़ोन नंबर',
  'relationshipSon': 'बेटा',
  'relationshipDaughter': 'बेटी',
  'relationshipGrandson': 'पोता / नाती',
  'relationshipGranddaughter': 'पोती / नातिन',
  'relationshipSpouse': 'पति/पत्नी',
  'relationshipOther': 'अन्य',
  'pleaseEnterCaregiverName': 'कृपया देखभालकर्ता का नाम दर्ज करें',
  'nameMinChars': 'नाम में कम से कम 3 अक्षर होने चाहिए',
  'pleaseEnterPhone': 'कृपया फ़ोन नंबर दर्ज करें',
  'validPhoneRequired': 'कृपया मान्य 10 अंकों का फ़ोन नंबर दर्ज करें',
  'passwordMinChars': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए',
  'passwordsDoNotMatch': 'पासवर्ड मेल नहीं खाते',
  'registrationSuccess': 'पंजीकरण सफल! कृपया लॉग इन करें।',
  'registrationFailed': 'पंजीकरण विफल',

  // Dashboard / Home
  'charge': 'चार्ज',
  'games': 'खेल',
  'activities': 'गतिविधियाँ',
  'reminders': 'अनुस्मारक',
  'family': 'परिवार',
  'talkToAssistant': 'सहायक से बात करें',
  'voiceGuideFor': 'इसके लिए वॉयस गाइड',
  'voiceOver': 'वॉयस ओवर',

  // Reminders
  'todaysReminders': 'आज के अनुस्मारक',
  'morningMedication': 'सुबह की दवा और गुनगुना पानी',
  'gardenStroll': 'बगीचे में हल्की सैर',
  'nutritiousLunch': 'पौष्टिक दोपहर का भोजन और फल',
  'brainHealthMemory': 'मस्तिष्क स्वास्थ्य मेमोरी गेम',
  'eveningMedicine': 'शाम की दवा और पारिवारिक कॉल',
  'medicineReminder': 'दवा अनुस्मारक',
  'hydrationReminder': 'जल अनुस्मारक',
  'doctorAppointment': 'डॉक्टर अपॉइंटमेंट',
  'drinkWater': 'एक गिलास पानी पिएं',
  'takeMedicine': 'निर्धारित दवा लें',
  'completed': 'पूर्ण',
  'pending': 'लंबित',

  // Family Sheet
  'myFamilyAndCare': 'मेरा परिवार और देखभाल',
  'noFamilyContacts': 'अभी तक कोई पारिवारिक संपर्क नहीं जोड़ा गया।\nदेखभालकर्ता डैशबोर्ड में संपर्क जोड़ सकते हैं।',
  'call': 'कॉल करें',
  'calling': 'कॉल किया जा रहा है',

  // Voice Companion Sheet
  'voiceCompanion': 'वॉयस साथी',
  'voiceListeningPrompt': 'मैं सुन रहा हूँ। मैं आपकी किस प्रकार सहायता कर सकता हूँ?',
  'voiceNews': 'आज के समाचार पढ़ें',
  'voiceMusic': 'शांत संगीत बजाएं',
  'voiceMedications': 'मेरी दवाएं जांचें',
  'voiceCallFamily': 'मेरे परिवार को कॉल करें',
  'processing': 'प्रक्रिया जारी है',

  // Settings
  'settings': 'सेटिंग्स',
  'theme': 'थीम',
  'light': 'लाइट',
  'lightDesc': 'काले टेक्स्ट के साथ साफ सफ़ेद पृष्ठभूमि',
  'dark': 'डार्क',
  'darkDesc': 'कम रोशनी वाला डार्क कंट्रास्ट मोड',
  'system': 'सिस्टम',
  'systemDesc': 'डिवाइस सिस्टम प्राथमिकताओं का पालन करें',
  'fontSize': 'फ़ॉन्ट आकार',
  'small': 'छोटा',
  'smallDesc': 'मानक कॉम्पैक्ट टेक्स्ट आकार',
  'medium': 'मध्यम (डिफ़ॉल्ट)',
  'mediumDesc': 'संतुलित पठनीयता और आराम',
  'large': 'बड़ा',
  'largeDesc': 'आसानी से पढ़ने के लिए बड़ा टेक्स्ट',
  'quickAccessApps': 'त्वरित पहुंच ऐप्स',
  'language': 'भाषा',
  'languageSubtitle': 'ऐप की भाषा चुनें',
  'english': 'English (अंग्रेज़ी)',
  'hindi': 'Hindi (हिन्दी)',
  'assamese': 'Assamese (অসমীয়া)',
  'bengali': 'Bengali (বাংলা)',
  'logout': 'लॉग आउट',
  'logoutConfirmation': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',

  // Games & Activities
  'memory': 'स्मृति',
  'attention': 'एकाग्रता',
  'executivePlanning': 'कार्यकारी योजना',
  'perceptualMotor': 'संवेदी-प्रेरक कौशल',
  'memoryGames': 'स्मृति खेल',
  'attentionGames': 'एकाग्रता खेल',
  'executiveGames': 'कार्यकारी खेल',
  'perceptualMotorGames': 'संवेदी-प्रेरक खेल',
  'beginActivity': 'गतिविधि शुरू करें',
  'sessionStarted': 'सत्र शुरू हुआ!',
  'startPlaying': 'खेल शुरू करें',

  // Games Detail & Dialogs
  'memoryHunt': 'मेमोरी हंट',
  'memoryHuntDesc': 'दिखाई गई वस्तुओं को याद रखें',
  'pairFinder': 'जोड़ी खोजक',
  'pairFinderDesc': 'कार्ड के मिलान वाले जोड़े खोजें',
  'pairFinderDialogDesc': 'समान कार्डों के जोड़े मिलाकर अपनी दृश्य स्मृति और मानसिक क्षमता को मजबूत करें।',
  'continuousFocus': 'निरंतर ध्यान',
  'continuousFocusDesc': 'जब चक्र हरा हो जाए तो टैप करें',
  'objectFocus': 'वस्तु ध्यान',
  'findDifferences': 'अंतर पहचानें',
  'findDifferencesDesc': 'दो चित्रों की तुलना करें और ध्यान केंद्रित करने के लिए सूक्ष्म अंतर खोजें।',
  'executivePlan': 'योजना और संगठन',
  'executivePlanDesc': 'दैनिक दिनचर्या की योजना बनाएं',
  'dailyTaskOrdering': 'दैनिक कार्य क्रम',
  'dailyTaskOrderingDesc': 'सुबह और शाम की आवश्यक दिनचर्या को सही क्रम में व्यवस्थित करें।',
  'activitySequencing': 'गतिविधि क्रमबद्धता',
  'activitySequencingDesc': 'रसोई, बागवानी और दैनिक कार्यों को शुरुआत से अंत तक सही क्रम में लगाएं।',
  'shapeMatching': 'आकार मिलान',
  'shapeMatchingDesc': 'आकारों को उनकी रूपरेखा से मिलाकर अपनी गतिशीलता और समझ को बढ़ाएं।',
  'dragAndPlace': 'खींचें और रखें',
  'dragAndPlaceDesc': 'वस्तुओं को छूकर टोकरी में खींचें और हाथ-आंख के समन्वय का अभ्यास करें।',

  // Pair Finder Tutorial & Game Extras
  'watchBeforePlay': 'खेलने से पहले देखें',
  'howToPlay': 'कैसे खेलें',
  'tutorialVideoNote': 'यह छोटा वीडियो देखें। वीडियो समाप्त होने पर खेल अपने आप शुरू हो जाएगा।',
  'elderlyPairTip': 'याद रखें: मिलते-जुलते कार्ड खोजने के लिए दो कार्डों पर टैप करें। आराम से खेलें!',
  'startPairFinder': 'जोड़ी खोजक शुरू करें',
  'gameStartsAuto': 'ट्यूटोरियल के बाद खेल अपने आप शुरू हो जाएगा।',
  'playLevelAgain': 'स्तर दोबारा खेलें',
  'startNextLevel': 'अगला स्तर शुरू करें',
  'backToGames': 'खेलों पर वापस जाएं',

  // Memory Hunt UI & Flow
  'levelXOf5': 'स्तर {level} / 5',
  'pleaseRememberObjects': 'कृपया इन {count} वस्तुओं को याद रखें',
  'pleaseRememberObjectsCarefully': 'कृपया इन {count} वस्तुओं को ध्यान से याद रखें।',
  'getReady': 'तैयार हो जाइए',
  'getReadyBreathe': 'तैयार हो जाइए! एक गहरी सांस लें।',
  'selectObjectsSawEarlier': 'पहले देखी गई {targetCount} वस्तुओं को चुनें ({selectedCount}/{targetCount})',
  'selectObjectsGuidance': 'पहले देखी गई {targetCount} वस्तुओं को चुनें। आपके पास {hintsRemaining} संकेत शेष हैं।',
  'hint': 'संकेत',
  'hintWithCount': 'संकेत ({count})',
  'gotIt': 'समझ गया',
  'hintXOf3': 'संकेत {index} / 3',
  'noHintsRemaining': 'कोई संकेत शेष नहीं',
  'allHintsUsedForLevel': 'आपने स्तर {level} के सभी 3 संकेत उपयोग कर लिए हैं। सही वस्तुओं को चुनने का प्रयास करें!',
  'usedAll3Hints': 'आपने इस स्तर के सभी 3 संकेत उपयोग कर लिए हैं।',
  'tryAgainExclamation': 'पुनः प्रयास करें!',
  'tryAgain': 'पुनः प्रयास करें',
  'tryAgainPrompt': 'यह पूरी तरह सही नहीं है।\nआपके पास {hintsRemaining} संकेत शेष हैं।\nमदद के लिए संकेत का उपयोग करें!',
  'tryAgainGuidance': 'पुनः प्रयास करें! मदद के लिए संकेत का उपयोग करें। आपके पास {hintsRemaining} संकेत शेष हैं।',
  'useHintWithRemaining': 'संकेत लें ({count} शेष)',
  'wellDoneExclamation': 'बहुत बढ़िया!',
  'youRememberedCorrectly': 'आपने बिल्कुल सही याद रखा!',
  'wellDoneGuidance': 'बहुत बढ़िया! आपने बिल्कुल सही याद रखा।',
  'foundAllLevelObjects': 'आपने स्तर {level} की सभी {count} वस्तुएं ढूंढ लीं!',
  'foundAllFinalObjects': 'आपने अंतिम स्तर की सभी 10 वस्तुएं ढूंढ लीं!',
  'nextLevel': 'अगला स्तर',
  'goodTryExclamation': 'अच्छा प्रयास!',
  'allHintsFinishedForLevel': 'इस स्तर के सभी 3 संकेत समाप्त हो चुके हैं।',
  'allHintsFinishedGuidance': 'सभी संकेत समाप्त हो गए हैं। सही वस्तुएं थीं: {answers}',
  'retryLevel': 'स्तर दोबारा खेलें',
  'continueText': 'आगे बढ़ें',
  'congratulationsExclamation': 'बधाई हो!',
  'allLevelsCompleted': 'आपने मेमोरी हंट के सभी 5 स्तर पूरे कर लिए हैं!\nआपकी याददाश्त बहुत तेज और मजबूत है।',
  'allLevelsCompletedGuidance': 'बधाई हो! आपने मेमोरी हंट के सभी 5 स्तर पूरे कर लिए हैं!',
  'playAgain': 'फिर से खेलें',
  'answers': 'उत्तर',
  'correctObjectsWere': 'सही वस्तुएं थीं:',

  // Memory Hunt Catalog Items
  'item_apple': 'सेब',
  'item_book': 'किताब',
  'item_ball': 'गेंद',
  'item_cup': 'कप',
  'item_car': 'गाड़ी',
  'item_dog': 'कुत्ता',
  'item_clock': 'घड़ी',
  'item_flower': 'फूल',
  'item_house': 'घर',
  'item_tree': 'पेड़',
  'item_sun': 'सूरज',
  'item_star': 'तारा',
  'item_bird': 'चिड़िया',
  'item_fish': 'मछली',
  'item_hat': 'टोपी',
  'item_key': 'चाबी',
  'item_chair': 'कुर्सी',
  'item_boat': 'नाव',
  'item_train': 'रेलगाड़ी',
  'item_umbrella': 'छाता',
  'item_camera': 'कैमरा',
  'item_guitar': 'गिटार',
  'item_shoe': 'जूता',
  'item_phone': 'फ़ोन',
  'item_bicycle': 'साइकिल',
  'item_lamp': 'दीपक',

  // Memory Hunt Level Hints
  'hint_1_1': 'एक वस्तु पन्नों वाली किताब है जिसे आप पढ़ते हैं (किताब)।',
  'hint_1_2': 'एक वस्तु स्वस्थ और मीठा लाल फल है (सेब)।',
  'hint_1_3': 'तीसरी वस्तु गोल है और बाहर खेलने में काम आती है (गेंद)।',
  'hint_2_1': 'आसमान और समय की दो वस्तुएं देखें: चमकता सूरज और टिक-टिक करती घड़ी।',
  'hint_2_2': 'प्रकृति की दो वस्तुएं देखें: एक सुंदर फूल और हरा-भरा पेड़।',
  'hint_2_3': 'एक आरामदायक घर है जहां लोग रहते हैं।',
  'hint_3_1': 'आकाश और पानी के जीव देखें: चहकती चिड़िया और तैरती मछली।',
  'hint_3_2': 'रात के आकाश में चमकता तारा और पानी पर चलती नाव देखें।',
  'hint_3_3': 'दैनिक उपयोग की वस्तुएं: पहनने की टोपी, दरवाज़े की चाबी और बैठने की कुर्सी।',
  'hint_4_1': 'सवारी के साधन: पटरी पर दौड़ती रेलगाड़ी और दो पहियों वाली साइकिल।',
  'hint_4_2': 'संगीत और तस्वीरें: तारों वाला गिटार, कैमरा और कमरे का दीपक।',
  'hint_4_3': 'दैनिक वस्तुएं: बारिश के लिए छाता, चलने के लिए जूता और बात करने के लिए फ़ोन।',
  'hint_5_1': 'प्रकृति और आकाश: चमकता सूरज, रात का तारा, हरा पेड़ और उड़ती चिड़िया।',
  'hint_5_2': 'मनोरंजन और यात्रा: सुरमयी गिटार, तस्वीर खींचने का कैमरा और रेलगाड़ी।',
  'hint_5_3': 'रोज़मर्रा की चीज़ें: स्वादिष्ट सेब, टिक-टिक करती घड़ी और बारिश का छाता।',

  // Activities Screen
  'activitySelectVoice': 'वॉयस निर्देश: थेरेपी शुरू करने के लिए कोई गतिविधि चुनें।',
  'reading': 'पठन',
  'readingRecall': 'पठन और स्मरण',
  'readingRecallDesc': 'छोटी, सुखद सांस्कृतिक कहानियों का आनंद लें और सौम्य स्मरण प्रश्नों के उत्तर दें।',
  'familyPicture': 'पारिवारिक\nतस्वीर',
  'familyPictureRecognition': 'पारिवारिक तस्वीर पहचान',
  'familyPictureRecognitionDesc': 'पारिवारिक एल्बम देखें, पुरानी यादों को ताज़ा करें और प्रियजनों से जुड़ें।',
  'music': 'संगीत',
  'musicSingingMemory': 'संगीत और गायन स्मृति',
  'musicSingingMemoryDesc': 'परिचित लोक धुनों और गीतों को सुनें जो भावनात्मक यादों को ताज़ा करते हैं।',
  'dailyRoutineRecall': 'दैनिक दिनचर्या\nस्मरण',
  'dailyRoutineRecallTitle': 'दैनिक दिनचर्या स्मरण',
  'dailyRoutineRecallDesc': 'दैनिक कार्यों को याद करें: नाश्ता, बगीचे की सैर, दवा लेना और पारिवारिक बातचीत।',
};

